### ISSUE TITLE
Code presenting broken for YAML

### ISSUE THREAD

**Issue by zeljkot** [gitpitch/gitpitch#102]
I have a presentation with some YAML and Java code. While Java markers scroll to correct place and highlight code, YAML does not scroll so highlight is not visible. Even when it is visible (at the beginning of the file), it is very faint.

Expected behavior:
* correct portion of the YAML file should be shown
* highlight should be more visible

It is visible in first code example in [this presentation](https://gitpitch.com/zeljkot/presentations/yaml-issue?&p=swagger)

**Comment by gitpitch** [comment]
Hi @zeljkot I suspect the issue is that  `highlight.js` (the underlying code highlighting library that is used by GitPitch) does not support YAML syntax in the core library. Given YAML is a superset of JSON you might be able to temporarily workaround this by using a JSON _language hint_ on your code delimiter.

For example:

```
---?code=swagger/example/complete.yaml&lang=JSON
```

You can learn more about using code-delimiter _language hints_ on the GitPitch Wiki [here](https://github.com/gitpitch/gitpitch/wiki/Code-Delimiter-Slides#code-highlighting-language-hint). For optimal rendering I recommend you use these on all code delimiters. Anyway, if you try this out and let me know how you get on.

**Comment by gitpitch** [comment]
FYI @zeljkot I will look into adding first class support for YAML syntax over the next few days. In the meantime, try the workaround described above.

**Comment by zeljkot** [comment]
It worked, thank you! And thank you for the quick reply! I am giving a presentation on Saturday and this really helped me!

**Comment by gitpitch** [comment]
Hi @zeljkot just to let you know that I've just pushed a patch that gives GitPitch native syntax highlighting support for YAML. This patch is now live on _gitpitch.com_. You can therefore use a `YAML` language hint for any future code blocks that contain YAML.

Note, the original workaround should continue to work as before although you may get improved syntax highlighting if you update your `PITCHME.md` to use a `YAML` hint.

Best of luck with your upcoming presentation.
