### ISSUE TITLE
Google Analytics Data - Did Something Stop Working?

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#117]
Since 10/7, none of my gitpitch presentations have recorded any traffic in Google Analytics.

https://github.com/gitpitch/gitpitch/wiki/Google-Analytics

Is it possible that something broke around that date?

**Comment by gitpitch** [comment]
Hi Terry, can you share a link to one of your presentations where you have activated Google Analytics in your `PITCHME.yaml` so I can investigate. Thanks.

**Comment by terrywbradyC9** [comment]
Thanks, @gitpitch.

https://github.com/terrywbrady/iiif-seajug/blob/master/PITCHME.yaml#L4

I see the following warning in Google Analytics.

> Tracking Code Mismatch error
Tracking code on page https://gitpitch.com does not match property Git Pitch Presentations's tracking ID UA-89672351-2.

**Comment by gitpitch** [comment]
Thanks @terrywbrady Just confirming I can reproduce the error you reported and I have a new patch pending release on gitpitch.com. This patch should be applied within the next 24 hours. The delay now is simply because I will need to bring down the live server to apply this patch so I need to choose a good time to do so. I will update this thread once the patch is live.

**Comment by gitpitch** [comment]
GA patch is now live, requires verification. @terrywbrady when you have a chance can you please check your GA dashboard and let me know if your token is now working again as expected.

**Comment by terrywbrady** [comment]
@gitpitch , I am seeing activity on GA again.  Thank you for the quick fix!
