### ISSUE TITLE
Help me understand the logic between GitPitch

### ISSUE THREAD

**Issue by m1guelpf** [gitpitch/gitpitch#120]
As an exercice, I'm trying to build a GitPitch-like application with Laravel, but I can't figure out how the application works (never used Java before 😞).

From the file structure, I'm supossing the framework you're using it's a MVC framework, but I'm stuck there.

It would be very helpful if you could explain me the request flow that happens when I request, for example, this repo's presentation.

**Comment by gitpitch** [comment]
Hi @m1guelpf

GitPitch has been designed to follow standard Play Framework conventions. So to begin, in order to understand the layout of the project itself I recommend the following article, [Anatomy of a Play Application](https://playframework.com/documentation/2.5.x/Anatomy).

If you really want to understand how it all works you will have a _lot_ to learn. And undoubtedly the best place to start is with the official Play Framework [documentation](https://playframework.com/documentation/2.5.x/Home).

More generally, I'd imagine you would be better off embracing Laravel conventions in your design and approach for whatever exercise you are working on. Honestly, GitPitch functionality is probably not a great candidate for a learning exercise given it's inherent complexity. Far too complex for me to explain here.

Best of luck with all things Laravel. I've heard great things about that framework.

**Comment by m1guelpf** [comment]
@gitpitch I've managed to understand everything but the asset organization. Could you explain what assets could be pulled from npm, what assets have been modified, what assets have been created and why you have like 3 different versions of some assets?
Thank you!

**Comment by gitpitch** [comment]
GitPitch works with many versions of the same assets to support distinct use cases and features at runtime. I'm not familiar with npm or how it manages assets.
