### ISSUE TITLE
In-step highlighting of multiple code fragments

### ISSUE THREAD

**Issue by jacg** [gitpitch/gitpitch#123]
I am looking for the ability to highlight code fragments **simultaneously** in two separate code blocks on the **same slide**.

My use cases include:

+ Compare and contrast equivalent code in two different languages
+ Relate source code to the output it generates

(In the latter case one of the blocks isn't really *source code*.)

Do you think that this might ever be supported?

**Comment by gitpitch** [comment]
Hi @jacg thanks for yet another interesting feature request. It so happens I am in the early stages of working on major new GitPitch release. That release will introduce a number of new features, including some subscription-only features, one of which I've provisionally named `synchronized code-presenting`. 

I believe this new `sync` feature will give you the kind of behavior you have described. For example, what I envisage for `synchronize code-presenting` would support the following types of scenarios: 

#### 1. Input -> Output
Stepping through a shell script and simultaneously seeing the corresponding console output being automatically updated.

#### 2. Code -> State
Stepping through code and simultaneously seeing state changes or corresponding console output.

#### 3. Code - > Code
Stepping through simultaneous code blocks, loops, functions for side-by-side comparison, discussion.

As you can see these are all variations on a theme, what I call (for want of a better name) `synchronized code-presenting`. And I think this will handle your uses cases as long as the `outputs` you referred to are text-based outputs.

I do not yet have a date for this upcoming relase but I will update this thread and the GitPitch blog with further news as it becomes available. Just fyi, this same release will also be adding support for a number of subscription-only features built around GitPitch presentations being served from within private repos which may also be of interest? Cheers, David.

**Comment by jacg** [comment]
Hi David, (I'm assuming that you get these without being @mentioned explicitly)

The features you mention look very interesting, and indeed closely related to what I wanted.

Presenting from private repos is not of particular interest for me at present. Indeed, my current needs are mostly towards the other end of the openness spectrum, so much so that I'm just *slightly* worried by hearing about *subscription-only features*.

I do not mean this to be critical in the slightest, and respect your choice of business model; I'm merely mentioning how it relates to my *current* needs, which may evolve in the future.

Could you point me to some info on how your subscription model works?

**Comment by gitpitch** [comment]
Hi @jacg thanks for this great feedback. In truth one of the reasons I mentioned some of the upcoming subscription-only features was to start having this type of conversation with my users.

I think the single, most important clarification I need to make right now is this:

> All of the features you freely enjoy today on gitpitch.com will continue to be free. Free as in beer. For everyone. Just like today. 

I hope understanding this alone will help calm some of your initial concerns.

Having worked full-time and entirely _gratis_ on GitPitch for almost two years now, covering all costs of development, maintenance, and hosting of the service itself on gitpitch.com, I believe I have made a reasonably large contribution to open-source and to the broader developer community on Git. A contribution happily made.

But I now need to pivot some of my efforts towards something that will deliver a sustainable income stream. Without this, I simply can not continue. And if I can not continue, neither can GitPitch.

So my main focus today is to make sure GitPitch can continue to delight an ever growing community of presentation geeks on Git, now and long into the future.

Rather than just flipping-a-switch and saying *free-no-more-time-to-pay* for the current feature set I am building new and enhanced features. These new features will obviously be above and beyond the current feature set. And this approach ensures I can _offer-real-added-value_ to users who choose to become subscribers. This approach also ensures that I can do this without taking anything away from users who decide to remain on the free plan.

I'm not in a position to announce further details of the subscription model today as it remains a work-in-progress, but as with many offerings online, there will be a number of plans, providing real choice for users.

And of course, one choice will be to simply continue as today, happily and freely enjoying all that GitPitch has to offer right now.

So I'm not sure where you will eventually land when GitPitch Pro rolls out, but at the very least I hope you will continue to enjoy using the service at some level, long into the future.

I recommend you keep an eye on the [GitPitch Blog](https://medium.com/@gitpitch) for further announcements. Or of course, you can follow me on [Twitter](https://twitter.com/gitpitch) for the same news updates.

**Comment by jacg** [comment]
Hi David,

While I suspect that it is unlikely that I will be signing up for GitPitch Pro myself on the day it rolls out (other tools currently still seem better suited for my current needs, overall), I really do wish you success in this endeavour: you have made something useful, worthwhile and beautiful, and from my perspective, cosmic justice would be done if you could make it a financial success too.

As an aside, have you considered somehing like a Kickstarter campaign? I mention this because I was really grateful that the [Kickstarter campaign for Magit](https://www.kickstarter.com/projects/1681258897/its-magit-the-magical-git-client) gave me an opportunity to offer financial support for the effort behind one of my most useful tools.

On a sociological note: the author embedded a subtle and easily permanently-suppressable (with visible instructions on how to do it) heads-up note about the existence of the campaign, in the software itself. This got one or two *very* negative reactions, even though most seemed to thnk it was a reasonable thing to do.

I seem to recall from browsing the issues here, that your need for visibility sometimes causes minor friction with users' needs, so I wish you the best of luck in navigating this minefield.

It's a shame that creators of value must, all too often, divert much of their effort into monetizing their product. I suspect that both you and your users would be happier if you could concentrate on making GitPitch even better, rather than on coming up with schemes for ensuring that you can pay your bills.

I wonder whether society will come up with better solutions to this general problem, any time soon.

**Comment by gitpitch** [comment]
Thanks again for this useful feedback and helpful suggestions. Here's to navigating minefields and cosmic justice :)
