### ISSUE TITLE
Shared `PITCHME.yaml`

### ISSUE THREAD

**Issue by lexsys27** [gitpitch/gitpitch#131]
I have several presentations in one repo. They are in a separate directory each. Like this:

```
.
|-1
| |-PITCHME.yaml
| |-PITCHME.md
|-2
| |-PITCHME.yaml
| |-PITCHME.md
|-3
  |-PITCHME.yaml
  |-PITCHME.md
```

All the presentations follow the same format so I want to use a single `PITCHME.yaml` for them. However, simply putting this file to the root directory and linking from the children's doesn't work. Any ideas how to do this?

```
.
|-PITCHME.yaml
|-1
  |-PITCHME.md
|-2
  |-PITCHME.md
|-3
  |-PITCHME.md
```

**Comment by lexsys27** [comment]
https://developer.github.com/v3/repos/contents/#response-if-content-is-a-symlink

Looks like GitHub sends special type `symlink` if the file requested is linking to another file. `DiskService` doesn't check this parameter and assumes it is the standard `file`, downloads its contents (which is the path to file) and drops it as invalid YAML.

I see several ways to implements the requested feature:

1. Make `DiskService` symlink aware
2. Add HTTP parameter for `PITCHME.yaml` location
3. Search for `PITCHME.yaml` like shared assets

I would like to hear your feedback.

**Comment by gitpitch** [comment]
I thought I had pushed support for a single `PITCHME.yaml` shared across multiple presentations within a single repo a long time ago. But I found those changes sitting in a local branch, as-yet unmerged. My bad. Those changes have just been merged.

The new behavior is simple and can be summarized as follows:

If the `p` parameter is specified for a `PITCHME.md` on a presentation:

1. GitPitch will first look inside the `p` directory for a corresponding `PITCHME.yaml` file. If that file is found it will be used to render the presentation.

2. If that file is not found, GitPitch will automatically search for a `PITCHME.yaml` in the root directory of the repo. This is the default location by convention. If found, it will be used to render the presentation.

3. Otherwise, the presentation will be rendered without `PITCHME.yaml` configuration.

With this new support in place you should be able to do exactly what you need, share a single `PITCHME.yaml` across any number of presentations within your repo.

Note, these changes have been merged into master but are not yet live on gitpitch.com. As you are running your own local server you can just pull these changes and then you should be able to test and verify locally. Let me now how it goes so we can update this thread.

**Comment by lexsys27** [comment]
I have verified the new behavior and it works perfectly! Thank you

**Comment by AdamSmith89** [comment]
@gitpitch In your last comment on this issue you mentioned the changes weren't live on gitpitch.com yet. Did this ever get pushed to live? I'm not using my own local server and seeing the same issue.

For reference my repo is [https://github.com/AdamSmith89/DailyCpp](https://github.com/AdamSmith89/DailyCpp.). The PITCHME.yaml is the the root directory of the repo and I've got a PITCHME.md in sub-directory "topics/optional". I've updated the theme in yaml to be a black theme but that isn't reflected in the "optional" sub-presentation.

Here is the presentation using the PITCHME.md in the root of the repo - [https://gitpitch.com/AdamSmith89/DailyCpp#/](https://gitpitch.com/AdamSmith89/DailyCpp#/).
![image](https://user-images.githubusercontent.com/24701281/60817960-934c6580-a194-11e9-8b77-3a4c4747e14d.png)

Here is the presentation using the PITCHME.md from the sub-directory - [https://gitpitch.com/AdamSmith89/DailyCpp/master?p=topics/optional#/](https://gitpitch.com/AdamSmith89/DailyCpp/master?p=topics/optional#/).
![image](https://user-images.githubusercontent.com/24701281/60818046-c5f65e00-a194-11e9-809b-71da0a724165.png)

**Comment by gitpitch** [comment]
Hi Adam, I think you hit some caching on the gitpitch.com server. If you try again you should see the `topics/optional` deck inherit the settings from the `PITCHME.yaml` in the root directory of your repo.

**Comment by AdamSmith89** [comment]
Yep that looks to be working now. Thanks for the quick reply!
