### ISSUE TITLE
Offline export for multiple modules

### ISSUE THREAD

**Issue by lexsys27** [gitpitch/gitpitch#133]
I have following structure for multiple modules sharing single directory with assets:

```
.
|-images
|-module
  |-PITCHME.md
```

When I export module for offline viewing images assets are not copied to the archive. I need to copy them manually:

```
cp images/* offline/$module/assets/md/assets
```

Direct solution is to handle this situation at GitPitch but even better solution would be exporting several modules from a single repository as a single archive with shared assets. For now I have N archives (N is number of modules) each having its own copy of assets.

**Comment by gitpitch** [comment]
I haven't been able to reproduce this problem here as all images are present for my own offline testing. So I'm going to need more data. Can you please provide a clean set of **debug** logs that capture just the activity that occurs when you click `Offline Version` in the menu. I'd like to see whatever clues it provides. If this is a large file you can e-mail it to me directly.

**Comment by lexsys27** [comment]
I will try to create a sample presentation, reproduce the problem and send you the link to this presentation with the instructions how to reproduce the issue.

**Comment by lexsys27** [comment]
For public repo this works fine, issue appears only when using private repo. It looks like the root issue is how GitPitch treats links to the images in the private repo - it doesn't add token and gets 404.

I have created another [issue](https://github.com/gitpitch/gitpitch/issues/135) for images in the private repo because it is slightly different from this one.

**Comment by gitpitch** [comment]
I want to first clarify, private repos are not yet supported by GitPitch. 

Appending tokens to URLs within a presentation that then access content within a private repo is inherently insecure. All presentation URLs are public, and as such any tokens used this way become public too. Given tokens grant read (and sometimes write) access to repos, my general recommendation is to avoid using tokens in this way.

To next major GitPitch release will add support for private repos in a manner that ensures that there is no exposure to token intercept or abuse.

@lexsys27 given you are running a local GitPitch server (operating under your own master token) you can of course access private repos associated with that single token. So if you can accomplish what you need  using tokens on urls, then that's great. But this approach will not be adopted by GitPitch.

**Comment by lexsys27** [comment]
Ok, I changed the strategy - now I server all the images from the public S3 bucket. The link is opened to the world and I can get this image with Chrome in private mode. 

And I see GitPitch gets 400 from S3 while trying to prepare offline version - no images in the archive.

To reproduce the issue I have created small public repo.

1. Go to https://gitpitch.com/lexsys27/gitpitch-temp?p=module01 - I see the image
2. Click "Offline Version"
3. Unpack archive
4. Open `index.html` in the browser - I see the placeholder

**Comment by lexsys27** [comment]
Sure - I am aware that private repos are not yet supported. I am just playing with the technology and thank you for all the help you provide! :)

**Comment by gitpitch** [comment]
I just tried your test presentation offline and it all worked fine for me. 

> Open index.html in the browser - I see the placeholder

I wonder, did you follow the instructions on the [Slideshow Offline](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Offline) wiki page that explains the need to start a local web server to open the index.html of your offline presentations?

> Sure - I am aware that private repos are not yet supported. 

No problem. I just want to make sure that your comments here do not confuse other users of GitPitch which is why I clarified the state of current and planned support for private repos.
