### ISSUE TITLE
Theme override .css not loading

### ISSUE THREAD

**Issue by Elaniobro** [gitpitch/gitpitch#139]
Looking to override the theme style with custom `.css`, yet when I load the gitpitch, I do not see the custom `.css` file loading in the network inspector. Is there something I am doing incorrectly?

`PITCHME.yaml`:
```
theme-override : css/PITCHME.css
background: images/Background.png
```
file architecture:
<img width="738" alt="screen shot 2017-11-30 at 11 52 47" src="https://user-images.githubusercontent.com/710847/33443215-0787e08e-d5c5-11e7-9591-2633ba8e4e53.png">

Thank you in advance for your help.

**Comment by gitpitch** [comment]
Hi @Elaniobro your custom CSS is automatically inlined on the main presentation page by GitPitch so there is no additional loading over the network. You should see the effects of your custom styling when you view your presentation content. Because of inlining, you will not see any indication of your custom css file being loaded in the network inspector.

If you feel your custom css is not being reflected in your presentation content then please provide a link to a sample presentation and I will take a look.
