### ISSUE TITLE
relative image urls seem to be broken since I checked last (24h ago) ...

### ISSUE THREAD

**Issue by ahojsenn** [gitpitch/gitpitch#153]
I get a redirect to https://gitpitch.com/pitchme/cdn/bitbucket/kommitment/verticals/master/img/abstract.png

rather than the relative link...

**Comment by gitpitch** [comment]
Thanks for this feedback. Rendering of relative images within Bitbucket presentations is a known issue and is being worked. The issue is related to following:

<img width="588" alt="gpe-status" src="https://user-images.githubusercontent.com/19169584/35477661-a79d2c2e-03fa-11e8-9644-2b6c50d3dd85.png">

**Comment by gitpitch** [comment]
Issue with relative images on Bitbucket resolved.
