### ISSUE TITLE
TTS (text-to-speech) feature

### ISSUE THREAD

**Issue by insertnick** [gitpitch/gitpitch#154]
Feature request: add TTS capability.

Text to speech would be useful in presentations.

Also, it would be nice for visually impaired people.

**Comment by Ryuno-Ki** [comment]
Hm, I am currently working on a [rewrite of articulate.js](https://github.com/Ryuno-Ki/articulate.js/tree/modernised-implementation). Thereby removing the hard dependency on jQuery and allow usage with SPAs.

@gitpitch Would be handy to learn on how you would integrate TTS in GitPitch? Maybe I can architect the rewrite in a way that would suit your use case :-)

**Comment by gitpitch** [comment]
Hi André, your articulate.js rewrite sounds like a very interesting project.

With regards integrating with GitPitch - the best (and only viable) approach would to be deliver your new library as a [reveal.js plugin](https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware).

The added benefit of this approach is that both pure reveal.js users and GitPitch users could make use of your work.

Btw, I did find this [existing tts plugin](https://github.com/jamjolu/tts_basics_for_revealjs) for reveal.js. I'm not sure *if-or-how-well* it works and I have never tried it with GitPitch but it might provide a good starting template for your own plugin efforts.

If you do decide to push ahead with a new TTS plugin please keep me updated - and I'll be happy to help out where I can.

**Comment by Ryuno-Ki** [comment]
Looking at its README and implementation, it looks like a basic implementation mainly focussing on the `textContent` of elements and `default voice`.

What I try to support (my itch is having it on my blog) is to allow different languages and take into account the semantics of HTML, i.e. a more full-fledged approach.

@insertnick Don't hesitate to mention me if the features takes too long to be implemented (or you are not hearing back from me). I have some more side projects running at the moment and could have got distracted by them.

So I'm going to look into what Reveal.js expects from its plugins in order to support it (but not write the plugin in the repo itself).

**Comment by dimensionetour** [comment]
@Ryuno-Ki as you proposed, here I am mentioning you given that the two conditions are both quite satisfied. Just in case you're now in a better position to contribute to this :)

**Comment by insertnick** [comment]
@Ryuno-Ki as you proposed, here I am mentioning you given that the two conditions are both quite satisfied. Just in case you're now in a better position to contribute to this :)

**Comment by gitpitch** [comment]
Just FYI, GitPitch now offers first class support for audio slide decks. Details in the [docs](https://gitpitch.com/docs/pro-features/audio/).
