### ISSUE TITLE
LaTeX / MathJax on gitpitch.com

### ISSUE THREAD

**Issue by dhidas** [gitpitch/gitpitch#161]
Greetings,

I have noticed that when using gitpitch.com and trying to subscript in latex it seems I run into trouble when trying to use more than one multi-character subscript.  I am using: mathjax : TeX-AMS_SVG.  Both of these work on mathjax.org and otherwise in latex.

Works:
$$ A_{n+1} = A_n + A_0 $$

Does not work:
$$ A_{n+1} = A_{n+0} + A_0 $$

Thanks for your help

**Comment by gitpitch** [comment]
Hi there. Can you provide a link to a presentation that reproduces the problem you have reported?

**Comment by dhidas** [comment]
Sure:

http://gitpitch.com/dhidas/GitPitchTest

**Comment by gitpitch** [comment]
And you mentioned there is a working example of this somewhere on mathjax.org. Again, can you please share a link. Thanks.

**Comment by dhidas** [comment]
$$ A_{n+1} = A_n + A_0 $$
$$ A_{n+1} = A_{n+0} + A_0 $$

You can cut and paste that into: https://www.mathjax.org/#demo

Both work on mathjax.org (and are valid latex)

**Comment by Takahiro-Itazuri** [comment]
Hello, dhidas!
I had a same problem.

In my case, the problem was solved by enclosing mathjax part in single back quote (`).
You can see examples in following URL.
https://github.com/gitpitch/kitchen-sink/blob/master/PITCHME.md

**Comment by keeeto** [comment]
I am getting this same problem. Indeed @Takahiro-Itazuri solution works, so $$ A_{n+1} = A_{n+0} + A_0 $$ becomes `$$ A_{n+1} = A_{n+0} + A_0 $$`. This does seem less than obvious though.

**Comment by gitpitch** [comment]
The underlying cause of this problem is a parsing issue when using the Reveal mathjax plugin within markdown. Which is the case when working with GitPitch. The original issues on this are [here](https://github.com/hakimel/reveal.js/issues/702) and [here](https://github.com/hakimel/reveal.js/pull/1205).

I have added a note to the [Mathjax page](https://github.com/gitpitch/gitpitch/wiki/Math-Notation-Slides) on the GitPitch wiki so in future users will be alerted to this issue rather than having to spend time to discover it.
