### ISSUE TITLE
"Slideshow Presentation Not Found" on BitBucket and GitLab

### ISSUE THREAD

**Issue by ryrych** [gitpitch/gitpitch#164]
Forked `in-60-seconds` presentation does not work when I log in using GitLab or BitBucket. It works for GitHub.

BitBucket user: tm_codeschool
Presentation: https://gitpitch.com/tm_codeschool/in-60-seconds

**Comment by gitpitch** [comment]
I do not see any public repositories under your account on Bitbucket:

<img width="1440" alt="screen shot 2018-04-06 at 9 17 39 pm" src="https://user-images.githubusercontent.com/19169584/38426162-1b988f72-39e0-11e8-914b-f68d281d85f5.png">

Is [https://bitbucket.org/tm_codeschool/](https://bitbucket.org/tm_codeschool/) your Bitbucket account?

What is the full path to your Bitbucket repo?

Note, if you want to access presentations within private repos on GitHub, GitLab, or Bitbucket you will need to activate a professional plan. Details on the GitPitch website [here](https://gitpitch.com/pricing).

**Comment by ryrych-themasters** [comment]
Hi,
I see that the account is now activated:

> Subscription Status: Active Plan: Professional

Presentation still doesn't work https://gitpitch.com/tm_codeschool/in-60-seconds.
Is there any way to contact you directly to get the support? I don't see any communication channels except Medium, Twitter, or GitHub issue. Direct feedback or help would help us sort things out better than communication over public channels. Do you have a slack channel? Please, share your e-mail, too.

**Comment by gitpitch** [comment]
Hi @ryrych-themasters , your subscription is indeed active and you can access your presentation on Bitbucket using the following URL:

[https://gitpitch.com/tm_codeschool/in-60-seconds?grs=bitbucket](https://gitpitch.com/tm_codeschool/in-60-seconds?grs=bitbucket)

Note, because your presentation is on Bitbucket, you must append a `grs` query parameter indicating that service. There is more information on the GitPitch wiki [here](https://github.com/gitpitch/gitpitch/wiki/Supported-Git-Services).

I am going to close this issue as it is not related to the open source GitPitch project. You can contact me directly by email: david at gitpitch dot com.
