### ISSUE TITLE
Can't fragment correctly lines with bold or italic elements

### ISSUE THREAD

**Issue by xgouchet** [gitpitch/gitpitch#166]
When I have a list item with a bold or italic part, the `<!-- .element class="fragment" -->` doesn't work as expected : instead of making the whole line appearing, it only makes the last inline element appear. Eg : in the following code, only the bold element is gonna appear. 

```- Here's a list item that should *appear* soon <!-- .element class="fragment" -->```

I know that I can use a custom ```<li class="fragment">…</li>``` but then I have a mix of markdown and html, which is opposite to the goal of using GitPitch.

**Comment by gitpitch** [comment]
Hi Xavier, as currently documented [on the Wiki](https://github.com/gitpitch/gitpitch/wiki/Fragment-Slides#list-fragments-where-item-content-uses-rich-markdown) when you use rich (rather than plain text) markdown you need to adopt the more verbose syntax for fragment list items. I agree, this is not ideal.

**But I do have good news**. GitPitch.com already supports a number of special shortcut syntax tricks that improve life for presentation authors. Including simple syntax to apply directly apply full CSS classes, and even faster shortcuts to adjust text font size, and adjust font color, etc. I need to create doc for this but for now you can see the video on the [following page](https://gitpitch.com/desktop) on the GitPitch website for sample usage. 

To your specific question, there also exists a new shortcut syntax for fragment lists. You basically wrap any regular Markdown list items within an `@ul` and `@ulend` tag pair. For example:

```
@ul
- Here's a list item that should *appear* soon
- Here is **another** one
@ulend
```

This will automatically turn every item in the list into a fragment. And it will handle both plain and rich [bold, italics, links, etc] markdown content within those list items.

You can use an `@ol` and `@olend` tag pair for ordered lists. 

This approach is completely independent of the old `|` fragment syntax. This ensures full backward compatibility for existing presentations using the old syntax so they do not break. Once I have documentation in place I will update this thread with a link to the full doc for the new tags.

Note, these shortcut features are available on gitpitch.com only. If you host your own open source server you will not have access to these shortcuts, so stick with the long format.

**Comment by gitpitch** [comment]
See the following GitPitch presentation for a live demonstration of:

1. The new list fragment syntax plus 
1. The new list fragment custom styling syntax plus
1. The new list fragment-specific speaker notes.

You can view the [live presentation here](https://gitpitch.com/gitpitch/feature-demo/frag-shortcut-syntax).
