### ISSUE TITLE
Image Not Rendered in PDF

### ISSUE THREAD

**Issue by tjc1575** [gitpitch/gitpitch#17]
I cannot get images to render when using the 'print' function on an internal instance of GitPitch.

I am running my own instance of GitPitch connected to an internal GitLab instance. Everything works well until I try to print / save-to-pdf. I have a single slide that contains an image ( png referenced by a local path to the related repository ). When I view the presentation through GitPitch, the image shows up as expected. When I try to print it to pdf, everything gets saved out except the image gets replaced by the question mark placeholder. The server does not indicate that anything encountered any issues. I have put the image both as an embedded image and used it as a logo through yaml and have encountered the problem in either case

**Comment by gitpitch** [comment]
Hi @tjc1575

The GitPitch server has an external dependency on the [decktape](https://github.com/astefanutti/decktape) library. This external library is used by the GitPitch server to convert slideshows to PDF. If you have not already installed and configured this dependency on your local server then you will need to do the following:

1. Install [decktape](https://github.com/astefanutti/decktape) on your local server
2. Update the `gitpitch.decktape.home` property in your `conf/application.conf`

The installation instructions are clearly detailed in the [decktape README](https://github.com/astefanutti/decktape). As you will see, it's a very simple process. 

You can quickly test your `decktape` installation by running the following command line:

```
cd path/to/decktape

bin/phantomjs decktape.js https://gitpitch.com/pitchme/slideshow/github/gitpitch/gitpitch/master test.pdf
```

You should end up with a PDF document called `test.pdf` that contains the contents of a simple `Hello, World!` presentation that includes images. Note, this command line assumes that the `phantomjs` binary is in the `bin` directory alongside the `decktape.js` library. If you local setup is slightly different from this layout just update the command line to match your local env.

Once you have `decktape` installed you then need to update the `gitpitch.decktape.home` property in the GitPitch server configuration file. That file can be found here:

```
conf/application.conf
```

And here is the section of that file that you will need to update:

```
# GitPitch Custom Configuration
gitpitch {

  hostname = "localhost:9000"

  https = false

  storage {
    home = "/tmp/gitpitch/swap"
  }

  decktape {
    home = "../decktape"
  }
.
.
.
```

Simply update the path for `decktape.home` to the path to your `decktape` installation on your local server.

Once you have `decktape` installed and you have made the necessary change to your configuration you can build and deploy your local GitPitch server one more time. You should then be able to print. Let me know how it goes.

**Comment by tjc1575** [comment]
Thanks for the reply @gitpitch 

I had already figured out the decktape dependency and updated the relevant path in the configuration file. I just ran the test phantomjs command you listed and it properly created the pdf including the images.

When I try to print from GitPitch it still doesn't work though. It saves out the rest of the presentation. It just doesn't include the actual images. 

Something that may be related: after going through the steps to print out the presentation the last time around I was getting an issue with resolving the url. The image wasn't showing up in GitPitch ( because it couldn't resolve the address ) and the printing of course failed. Once I logged into the GitLab instance in a different window it started resolving again.

Might the issue have something to do with the URL not resolving correctly when it is trying to print out the presentation?

**Comment by gitpitch** [comment]
@tjc1575 before we dig in any deeper can I just ask you to confirm that the repository where your slideshow presentation is contained is a `public` repo on your local GitLab server?

**Comment by tjc1575** [comment]
@gitpitch it was not, no. I had the repository as internal. Does it have to be public? The api token that was provided to GitPitch is from a user that has access to the repository. 

I went and made the repository public for testing. I am getting the same results. The image will appear for the GitPitch viewer but is missing in the pdf.

**Comment by gitpitch** [comment]
@tjc1575 GitPitch only works with `public` repositories so this is a required step regardless of what GP server you are pointing at.

Based on your feedback where you are (1) seeing expected results in the browser but (2) not seeing expected results in the PDF I thought (and still think) the issue may have to do with access. 

Are you logged in to GitLab within your browser where you are viewing the presentation? If so, can you try logging out of GitLab in the browser where you are testing/viewing your presenation (or trying another browser where you are not logged into GitLab) and let me know if you can still see your images in the browser?

When `decktape` executes it is executing in a isolated context and  will definitely not be operating with any `GitLab` credentials/cookies in the session.

Once you let me know what you see after performing the test described above we can work out how best to approach the issue.

**Comment by gitpitch** [comment]
@tjc1575 here is a quick test you can run that will also provide useful info to help us debug here. Can you please try the following to test/verify that public assets are available for download on the GitLab raw data API for your local GitLab server:

```
curl https://server/username/project/raw/branch/assets/image.jpg > image.jpg
```

Where:

- `https` or `http` depending on your local GitLab server setup
- `server` is the IP or hostname for your local GitLab server
- `username` is the GitLab username associated with your public test repo
- `project` is the GitLab project name associated with your public test repo
- `branch` is the GitLab repo branch where your test presentation lives
- `assets` is the repo directory where your test presentation image lives
- `image.jpg` is the name of your test presentation image file

Note, `branch` could be `master` or the name of a `feature branch` if you are using one of those.

We are using `curl` here so we can test outside of the browser. The `curl` call should either succeed in which case you will end up with a local copy of your image file. Or it will fail. And if it fails, we will want to understand (1) how it fails (what error code?) and then ultimately (2) why it fails.

**Comment by tcarpenter-chi** [comment]
@gitpitch okay, so I ran a few tests. I opened up a private browser window to ensure that there was no credentials / cookies bleed over. The GitPitch presentation was able to show the image; the printed pdf still did not show the image. 

I ran the curl command and was able to download the image correctly.

One thing of note came up when trying to print the pdf. The first time I clicked print in the private window I saw the following error message: 

`Loading page finished with status: success
Reveal JS DeckTape plugin activated
+- Unable to load resource from URL: http://source.chisystems.com/ice/ice/raw/master/assets/logo.png
|_ Error code: 3
|_ Description: Host source.chisystems.com not found
Printing slide #/0      (1/1) ...
Printed 1 slides
`

I don't know why there would be any name resolution errors though. I have an internal DNS server going and am not seeing any problems with it ( and the GitPitch presentation view can resolve it just fine ). It only happened once. I opened up a new private window and tried the same steps again and did not see the error.

**Comment by gitpitch** [comment]
Hi @tjc1575 

I can see from the `decktape` output that you are using the master branch for testing your presentation. PDF generation by the GitPitch server is subject to the following [caching policy](https://github.com/gitpitch/gitpitch/wiki/GitPitch-Caching#pdf-caching). So the reason you see that error from `decktape` only the first time is because the PDF for a presentation on the `master` branch is cached for up to 20 minutes. It is not regenerated every time you click `Print` and this is why I believe you do not see this error every time you click `Print`.

For your testing purposes I suggest using and testing against a feature branch so a new PDF will be generated by your server every 20 seconds.

So I think based on the error message from `decktape` this DNS issue is the root cause of your problem and I believe you will see this same error message every single time you cause your local GitPitch server to generate _a new PDF_ for your presentation. Again if you switch your testing to a feature branch you can quickly verify this.

There is one more test you could run that would prove this definitively. Change the `hostname` configuration in the `conf/application.conf` file to use the IP address that corresponds to `source.chisystems.com`. I suspect your current configuration looks as follows:

```
gitpitch {
  hostname = "source.chisystems.com"
```

Then restart your server and see if you can view and also print your presentation. If you can you will have near definitive proof that the issue is local DNS related.

**Comment by tcarpenter-chi** [comment]
@gitpitch Yep, that fixed it. I was trying with a feature branch yesterday and don't remember seeing the resolution error, but I must have missed it. Just to clarify, the issue was actually with the GP setup. I had to change the `site`, `apibase`, and `rawbase`, configuration values to use the IP rather than the host name. 

Any idea why it can't resolve the host?  ( All other systems, including the normal GitPitch presentation when not using print, can resolve the host )

**Comment by gitpitch** [comment]
@tjc1575 good to hear that it is now working for you. That change you made to the GP config really only changes the URLs that point at GitLab files. So instead of using a `hostname` those URLs would be constructed using `IP` addreses.

Those URLs are then used to load and render presentation content in your browser. And those same URLs are also used by `decktape` to embed the presentation content (in this case, image content) in the generated PDF.

Perhaps `decktape` is using these URLs in a custom way to load the corresponding data and that custom handling is failing somehow on name resolution. I'll ping the `decktape` guys and see if they can shed any further light on this.

**Comment by tjc1575** [comment]
@gitpitch okay, thanks for your help. The IP address is stable so this is a suitable work around for now. I'm closing the issue since this is really either an issue with my own local DNS ( which I don't think is the case since it works otherwise ) or an issue with name resolution in `decktape`.

**Comment by gitpitch** [comment]
Ok @tjc1575 I'll update this thread if I hear anything conclusive from the `decktape` folks.
