### ISSUE TITLE
Code Highlighter numbering issue with @.

### ISSUE THREAD

**Issue by AhmedBHameed** [gitpitch/gitpitch#171]
Hi,

I was building my own slider using Gitpitch which is very nice to make technical slider so THANK YOU.

my issue is when i write a code sample and then use @[From-To] as code highlighter i have to write the exact line number starting from the first line of the code.

Imagine that my code is a bit long, is there a way to use the same iteration of the IDE to indicate the line number of the code ??

Example if i'm standing on line 231 on my IDE i can start the code here and start referencing my highlight directly with the same number

```javascript
231  var myclass = (function() {
232  
233 // my code here
234  }())
```

@[232-233]

I know it might be hard for validation issues but if we can compiled it with a reference it might be easier to track.

Or please advice me with other way to implement this faster through slider design phase.

**Comment by gitpitch** [comment]
Hi Ahmed, nice to hear that you are enjoying using GitPitch.

If you use [code delimiters](https://github.com/gitpitch/gitpitch/wiki/Code-Delimiter-Slides) to inject code onto your slides ( instead of markdown code blocks ) then you can use the exact same line numbers in your GitPitch [code fragment markers](https://github.com/gitpitch/gitpitch/wiki/Code-Presenting#code-presenting-markdown-syntax) that you see in your IDE.

Does this give you what you need?
