### ISSUE TITLE
Possible type-o in wiki

### ISSUE THREAD

**Issue by solvingj** [gitpitch/gitpitch#178]
Do these two really have the same timeout of 15 seconds?  

https://github.com/gitpitch/gitpitch/wiki/GitPitch-Caching#slideshow-caching

```
Slideshow presentations on the master branch are cached for up to 15 seconds
Slideshow presentations on any feature branch are cached for up to 15 seconds
```

**Comment by gitpitch** [comment]
It is not a typo, both `master` and `feature branches` do currently share the same 15 second timeout.

#### Some background: 

When first released GitPitch cached `master` branch content for 90 seconds and feature branch content for just 15 seconds. The reasoning behind this caching policy was that `master` typically is used as a steady-state release branch, not as a development branch.

Well it turns out many people develop directly in `master`. This was a surprise to me at least. But once I realized this was how many users worked, I changed the GitPitch caching policy to support this (somewhat unexpected) workflow.
