### ISSUE TITLE
Footer Comments

### ISSUE THREAD

**Issue by tjc1575** [gitpitch/gitpitch#18]
Is there any way to add footers? I have to add a "proprietary" statement on each slide and I would like that to appear at the bottom. Is that possible? Can I set something up in the YAML or theme to do it? I tried adding an html block but the test just appears in the middle of the slide, right under the other content rather than at the bottom.

```
<div class="footer">
Proprietary
</div>
```
Along the same lines, is it possible to put in title bars? When headers are added they are centered in the slide. I would like to be able to add titles which show up at the top of the slide and are left aligned. This is less of an issue though as I can just change the formatting of my slides.

**Comment by gitpitch** [comment]
@tjc1575 I've just [added support](https://github.com/gitpitch/gitpitch/wiki/Footnote-Setting) for a new `footnote` setting that can be set in your **PITCHME.yaml**.

By setting a `footnote` message in that file your message will be applied to every slide, appearing in the bottom-left corner of each slide. If you test this out please let me know how it goes.

As for title bars, if you want a distinct title per slide you are probably best have to use custom css, [see here](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS#example-2-left-align-slide-content). If you want a title bar (or banner) for use across every slide in your presentation then you should consider using the [Logo Setting](https://github.com/gitpitch/gitpitch/wiki/Logo-Setting). This allows you to display a custom logo (or any image) that will appear on the top-left of every slide in your slideshow presentation.

**Comment by tjc1575** [comment]
@gitpitch Thanks for the quick turn around. I'll pull the newest version and test it in the morning. Is there, by chance, the ability to make the footnote appear centered along the bottom? Is there some way I can format to get that effect? I need to make sure the proprietary statement is easily seen.

As for the title bars. I am new to css, is it possible to set left align / top align just for the title? I am thinking that would be keeping the .slide formatting the same ( so that it doesn't change the entire slide ), and instead create a span with the left align. Does that make sense? I am trying to create a slide similar to Powerpoint where there is a left aligned title at the top of the slide and then centered text for the rest of the slide which is the main content.

**Comment by gitpitch** [comment]
Hi @tjc1575 due to the way the footnote is implemented there is no way to pull it to the center. When you have a chance to try it out (recommend using Fullscreen) I think you will see that the text is clear and legible.

I understand what you are trying to accomplish with your title. I don't know offhand how you might achieve that effect you want. If there is a way to achieve this it would have to take into account the default css styling rules on the page which are determined by the theme you are using when rendering your slideshow. I will try and look into this when time permits but it could be a while so I suggest you dig into it further. Using a tool like Firebug can be very helpful when you are trying to see what affect tweaking css has on a page.

**Comment by tjc1575** [comment]
@gitpitch the footer looks great. Tried it in both normal and fullscreen and it worked as expected. Thanks for the quick update.

**Comment by kenrim626** [comment]
I currently have a footnote configured, but it does not work on the first page, because the shortcut info is displayed. Is there a way to prevent this?

**Comment by gitpitch** [comment]
Hi @kenrim626 the navigation/shortcut info is always displayed on the first slide - to help presentation authors and audiences alike. There is currently no way to replace the navigation/shortcut message with your footnote.

**Comment by kenrim626** [comment]
@gitpitch Could you add it as a feature request? I would love to have that option in my PITCHME.yaml as it can be very useful for professional presentations.

**Comment by gitpitch** [comment]
@kenrim626 you can add it as a new feature request - just open a new issue to explain what you want and once I see it I'll label it accordingly. That will also give others a chance to upvote the request.

As an aside, are you are GitPitch Pro [subscriber](https://gitpitch.com/pricing)? I ask because feature that's are particularly useful for professional presentations are much more likely to be made available on the Pro service.
