### ISSUE TITLE
no logo on first slide

### ISSUE THREAD

**Issue by rzuritamilla** [gitpitch/gitpitch#182]
Hi there,

Gitpicht is nice! 
I am experimenting with it and cannot find an easy way to remove the logo from the first slide. Is this possible? 

Thanks!

**Comment by gitpitch** [comment]
Hi Raul, glad you are enjoying using GitPitch.

> remove the logo from the first slide. Is this possible?

The [logo setting](https://github.com/gitpitch/gitpitch/wiki/Logo-Setting) is global so as you have probably already found all slides are embossed with a logo image if this setting is activated.

So the short answer is that there is no quick fix for what you want to do.

You could try adding a `<div>` using `fixed` positioning  to overlay on top of the logo - in effect, hiding it.

Some [custom CSS](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS) like this - but keep in mind this is pseudo code - you will need to play around with the values to find something that works for your presentation:

```
.logo-eclipse {
    position: fixed;
    top: 10px;
    left: 10px;
    width: 150px;
    heigh: 50px;
    z-index: 99;
    background-color: black;
}
```

And then you could add the `<div>` as content on your first slide, something like this:

```
--- 

<div class="logo-eclipse"></div>

### Your First Slide Content Goes Here

```

In theory, this approach could be used to make the logo disappear from your first slide. But it is going to depend heavily on what other content/background images etc. you are using on the slide.

If you try it, let me know how it goes. Otherwise you can just close the issue as there is no other workaround that I can think of today.

**Comment by rzuritamilla** [comment]
Hi David,

Thank you very much for the very detailed answer. 
I am afraid that this solution is not really applicable to my case.
I have a background image in the first slide and this would be as "intrusive" as having the logo... 
I am not very familiar with HTML / CSS but perhaps we there are ways to either change the order of the layers (i.e. background image on top of the logo) or to paste another image on top of it... Alternatively, I could experiment with inserting a logo image (background?) in each of the core slides (i.e. excluding cover and end slide).

**Comment by gitpitch** [comment]
> I am afraid that this solution is not really applicable to my case.
> I have a background image in the first slide and this would be as "intrusive" as having the logo...

Understood. I realized when I was writing to you that if you were already using a background image on the first slide ( it turns out you are ) then a color mask would not work.

> I am not very familiar with HTML / CSS but perhaps we there are ways to either change the
> order of the layers (i.e. background image on top of the logo) 

You can not perform this kind of manipulation for just a single slide.

> or to paste another image on top of it... Alternatively, I could experiment with inserting a
> logo image (background?) in each of the core slides (i.e. excluding cover and end slide).

This approach could work. But it would mean that you could not use background images on any slides other than your first and last slide or the logo would disappear - as the logo would become the background slot for all of the other slides. You could of course [inline images](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#inline) on those slides.

To do what you want, you would use a combination of [global background settings](https://github.com/gitpitch/gitpitch/wiki/Background-Setting) to place a background logo image on every slide. And then you would override this global default using a [slide-specific background image](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#background) for your opening (and closing) slides.

For example, something like this for global settings in your **PITCHME.yaml**:

```
background : assets/image/logo.png
background-position : left top
background-size : 150px auto
```

These are just sample values. You will need to play around with them in order to find settings that work well with your logo image and slide content. Again, see the [image doc](https://github.com/gitpitch/gitpitch/wiki/Image-Slides) on the Wiki to understand the kinds of values you can use on these settings.

**Comment by Ryuno-Ki** [comment]
From a CSS point of view, you could use [several background-images](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image) (Haven't it tested on GitPitch, though).

The exact values would need to be figured out. However, there is no demo repo linked from the issue opener.

**Comment by rzuritamilla** [comment]
Hi David,

Apologies for the delay in getting back to you. I was away from my computer.
The solution based on the global background worked like a charm. Thanks!!!

@Ryuno-Ki: Thanks for sharing your CSS-based solution. I tried to implement it but somehow I could not make it that work...
