### ISSUE TITLE
Attempting to d/l pdf and offline versions failing

### ISSUE THREAD

**Issue by jerdog** [gitpitch/gitpitch#184]
No matter what browser I use (incognito or not) I keep getting the following screen when I attempt to download the offline and pdf versions of my slides

![image](https://user-images.githubusercontent.com/296864/41669562-b82dc89e-7477-11e8-88aa-6d0ca2af48e8.png)

Repo: https://github.com/jerdog/droidconde18

**Comment by jerdog** [comment]
And yes, I have refreshed the browser window multiple times - happens on Incognito as well

**Comment by gitpitch** [comment]
The problem stems from your use of the the following import statement in your custom *PITCHME.css* file:

```
@import url("fontawesome-all.min.css");
```

This relative url path is not supported. And it's presence is tripping up each attempt at print and download because the path not valid on your session - and so rejected.

You need to remove this import from your *PITCHME.css* file. 

I'm also curious, why are you not just using the [built-in font-awesome icon set](https://github.com/gitpitch/gitpitch/wiki/Font-Awesome-Icons)?

**Comment by jerdog** [comment]
Hmm - I could have sworn I didn't have that problem before I tried to import fontawesome - I was having some issues and thought I needed an updated list... Anyways - totally my fault here.
