### ISSUE TITLE
Math-object overflows

### ISSUE THREAD

**Issue by MrCode97** [gitpitch/gitpitch#202]
The math formula is not being fitted properly to the window size. In my case it is too big. Is that a bug or do I have to downscale it via css-file?

see: https://gitpitch.com/baloise/ws-itsec_owasp/awareness#/1/3

**Comment by gitpitch** [comment]
You can try dig into the MathJax CSS (using Web inspector etc) to see if you can override MathJax specific rules but I don't think that is going to work because MathJax adds a lot of style rules directly onto span elements rather than using classes - so I don't think there is any way you can override the rules.

My advice, create abbreviations for the variable names in your formulas. This should allow your formula to render within the space available on the slide. Then provide a key below your formula that maps the abbreviations to the more meaningful long names.

For example, use something like `avek` in place of `Angriffsvektor` and then add a explanatory note on your slide.

**Comment by MrCode97** [comment]
I'll do that. Was just wondering whether there was some other more elegant way or something I missed.
