### ISSUE TITLE
Distinct in and out transitions are not recognized

### ISSUE THREAD

**Issue by ElpyDE** [gitpitch/gitpitch#206]
I've come across something that feels like a bug to me.

When I try to define distinct _slide-in_ and _slide-out_ transitions, they seem not to be recognized and instead the default, defined in PITCHME.yaml, is used.

## Specifically:

* The `PITCHME.yaml` file defines the default transition to be `transition: fade`
* :ok: Slides with no specific `@transition` shortcut use the default
* :ok: Slides with a single `@transition[transition-type]` use this for their _slide-in_ and _slide-out_ transition as expected
* :x: Slides with distinct _slide-in_ and _slide-out_ transitions like `@transition[transition-type transition-type]` use the default for both which is not what I would expect from the docs

## Sample slide show:

https://github.com/ElpyDE/gitpitch-transitions/ ([View with GitPitch](https://gitpitch.com/ElpyDE/gitpitch-transitions/master))

## Additional observation

If I leave the `PITCHME.yaml` empty, the behavior gets even more erratic. Some slides then use the default `slide` transition and others `fade`. See branch [no-default](https://github.com/ElpyDE/gitpitch-transitions/tree/no-default) or [View with GitPitch](https://gitpitch.com/ElpyDE/gitpitch-transitions/no-default). This branch is otherwise equal.

## Related issues

The only related bug seems to be #196 where the _slide-in_ and _slide-out_ transitions are mentioned and seem to work.

---

PS: This bug aside... THANK YOU for GitPitch... it's really awesome!

**Comment by gitpitch** [comment]
Hi @ElpyDE I believe I'm the culprit here. Or at least my current documentation is misleading. If you are specifying distinct `in` and `out` transitions for your slides then I believe you are going to have to *postfix* an `-in` or an `-out` to the stand transition names.

For example, if you plan for a slide to `zoom` in and to `convex` out then the transition names you will need to use are `zoom-in` and `convex-out` respectively. So it would look like this in your **PITCHME.md**:

```
---
@transition[zoom-in convex-out]

### Your regular slide content.
``` 

Can you please try this approach within your sample presentation and let me know if the behavior of your slides is now as expected?

**Comment by ElpyDE** [comment]
That was it...

See here with your changes: https://gitpitch.com/ElpyDE/gitpitch-transitions/master

Thank you!

**Comment by gitpitch** [comment]
FYI, the [transition docs](https://gitpitch.com/docs/markdown-features/shortcuts#set-slide-specific-transition) have been updated to more clearly explain proper usage of *slide-in* and *slide-out* transitions.
