### ISSUE TITLE
code highlighting

### ISSUE THREAD

**Issue by MrCode97** [gitpitch/gitpitch#209]
Some parts (code) seem to get darker instead of the highlighted code being brighter / highlighted. I tried different browsers and also fewer highlighting-steps. 

Link:
https://gitpitch.com/baloise/ws-itsec_owasp/awareness#/5/10

Code:
```
+++?code=/res/snippets/oob-xxe.xml&title=Out of band XXE (XML)
@[1-7]
@[9-16]
@[1,4]
@[1,4-5]
@[3,10,12]
@[12,16]
@[13]
@[7]
@[7,10,13]
```
Screenshot:
**Step 1** `@[1-7]`
![step1_ 1-7](https://user-images.githubusercontent.com/25118350/44347171-75e8ad00-a497-11e8-8168-9e9f8ad90868.png)

**Step 2** `@[9-16]`
![step2_ 9-16](https://user-images.githubusercontent.com/25118350/44347173-75e8ad00-a497-11e8-9c8a-30b7af816ab8.png)

**Comment by gitpitch** [comment]
When the code you are trying to display on your slide is markup (such as XML) you need to add a language hint on your code delimiter to ensure that your markup is properly encoded for display (rather than rendering). See this discussion of [code delimiter language hints](https://gitpitch.com/docs/code-features/fenced-blocks/#code-syntax-highlighting) in the docs.

To fix the problems you are seeing, try:

```
+++?code=/res/snippets/oob-xxe.xml&lang=xml&title=Out of band XXE (XML)
@[1-7]
@[9-16]
@[1,4]
@[1,4-5]
@[3,10,12]
@[12,16]
@[13]
@[7]
@[7,10,13]
```

**Comment by MrCode97** [comment]
That works, thank you.
I must have missed it in the docs, I am sorry.

**Comment by gitpitch** [comment]
No problem. Glad to hear it's working for you now. Closing.
