### ISSUE TITLE
Ordered nested list not numbering correctly

### ISSUE THREAD

**Issue by menzzana** [gitpitch/gitpitch#215]
I have an issue with indentation of a numbered list...
I have this list
```
@ol[](false)
- Item1
  - subitem1
  - subitem2
-item2
@olend 
```

This shows as 
```
1. Item1
    2. subitem2
    3. subitem3
4. item2
```
Tried different numbers of indentations and empty lines, but still the numbering is wrong

**Comment by gitpitch** [comment]
Hi Henric, to clarify - can you please share an example of what it is you are expecting to see? Thanks.

**Comment by menzzana** [comment]
Yes, sorry for not making it clearer!
The output for the above mentioned list I would expect to be ...
```
1. Item1
    1. subitem1   (or 1.1 subitem1)
    2. subitem2   (or 1.2 subitem2)
2. Item2
```
Is that possible?

**Comment by gitpitch** [comment]
Thanks for the clarification. I don't have a way for you to do what you want right now but I will try to take a look over the coming week to see if it might be done. I will update this thread with what I find.

**Comment by menzzana** [comment]
Thanks for looking into it. Perhaps I bring it up but I would guess most people using indented ordered lists would expect that kind of output that I am describing.

I must say after trying different presentation software (Hieroglyph/Sphinx, Latex, etc...) Gitpitch is so far the best of the lot and I might have some further suggestion, which I think, could make it even better.

**Comment by gitpitch** [comment]
A quick update for this thread. I have looked into what would be involved to support the rendering of indented ordered lists as you described. And I agree, what you describe would indeed be an improvement if the GitPitch shortcut syntax for lists could support this type of rendering.

That said, this is not something that can be easily accomplished without introducing a risk to backward compatibility for existing presentations. So rather than committing to developing such a fix today I plan to leave this thread open to give the GitPitch community an opportunity to upvote the issue. If it attracts sufficient interest I will revisit the issue and consider moving it up the priority list. 

In the meantime, given GitPitch already provides support for *HTML snippets* you can easily create the desired rendering effect using these snippets directly within your **PITCHME.md**.

For example, you could use the following:

```html
<ol style="list-style-type: decimal">
    <li>One</li>
    <li>Two
        <ol style="list-style-type: lower-roman">
            <li>Two point One</li>
            <li>Two point Two</li>
        </ol>
    </li>
    <li>Three</li>
    <li>Four</li>
</ol>
```

And the output on your slide would look something like this:

<img width="492" alt="screen shot 2018-09-21 at 9 07 05 am" src="https://user-images.githubusercontent.com/19169584/45868529-e0825680-bd7d-11e8-9fae-c4bb33ec5d93.png">

Not identical to what you described, but certainly very much in the spirit of the desired outcome.

**Comment by gitpitch** [comment]
Hi André, thanks for this helpful tip. CSS counters will likely be part of the eventual solution.

**Comment by gitpitch** [comment]
This issue has been resolved. Using the following syntax for an ordered, nested list:

```markdown
@ol[](false)
1. Item1
   1. subitem1
   1. subitem2
1. Item2
@olend 
```

Renders as follows:

![ordered-nested-lists](https://user-images.githubusercontent.com/19169584/80313288-e8b83880-87e1-11ea-87d6-a3ac541635ec.png)

As noted in the [Markdown List Widgets Guide](https://gitpitch.com/docs/markdown-features/list-widgets/) you must indent nested list content using _4 spaces_ in your markdown file.
