### ISSUE TITLE
Problem Displaying Images from HTML

### ISSUE THREAD

**Issue by Twonki** [gitpitch/gitpitch#221]
Hey there, 
so the doc is a little lacking when talking about pictures with html.
 
I'm trying to display multiple images throughout my presentation using the html <img/> and usualy box them in divs. 

However, the Items are not loaded, i just see "missing-Images" for most of my images added this way. 
Heres the presentation with relative sourcelinks: https://gitpitch.com/Twonki/EdgeDetection/master#/2/2
Heres the presentation with hardlinks into my repo: https://gitpitch.com/Twonki/EdgeDetection/draft#/2/2

Heres my Repo's Pitchme.md: https://github.com/Twonki/EdgeDetection/blob/master/PITCHME.md 

Notable is that every md-linked image worked fine, and some images (Prewitt) are displayed too, even though i never changed my use of it.

**Comment by gitpitch** [comment]
Hi, here's some feedback that will hopefully be of some help.

First, if you are using relative paths to images (which I always recommend for repo assets) within HTML `img` tags then _make sure_ you do not indent the tags in your markdown file. GitPitch will only pre-process relative paths on HTML `img` tags that start a new line in your `PITCHME.md` file. For example, _don't do this_:

```
<div>
    <img src="img/pic.png">
</div>
```

Do this instead:

```
<div>
<img src="img/pic.png">
</div>
```

Second, don't use HTML `img` tags :-)

I recommend you use standard markdown inline image syntax instead. For example:

```
![](img/pic.png)
```

Third, if you need to style your inline images on a slide I recommend using [custom css](https://gitpitch.com/docs/themes/custom/) rather than adding styles directly onto your elements. For example, you could define a custom style as follows:

```
.slidepic img {
  width: 30%;
  height: 30%;
  border: none;
  box-shadow: none;
}
```

Then you could apply that custom style to your inline image as follows:

```
@div[slidepic]
![](img/pic.png)
@divend
```

Note, the use of `@div` is just a syntax shortcut, it is equivalent to using `<div class="slidepic">...</div>`.

This approach is syntactically cleaner, gives you much great reusability of styles, and is easier to maintain over time.

As a side note, I noticed you are using `<div>` elements extensively within your `PITCHME.md` file. And I'm not sure why. For example, what is the purpose of all the `divs` in the following snippet:

```
+++
<div>
<div><h3> Problem I: similiar colours</h3></div>
<div>
    <img src="images/simcolour.png" style="width: 60%; height: 60%; margin-top: 0px; border: none; background: none; box-shadow: none;"/> 
</div>
</div>
```

You could try an approach more like this:

```
+++

### Problem I: similiar colours

@div[colorpic]
![](images/simcolor.png)
@divend

```

One final tip, I spotted this in your `PITCHME.md`:

```
@snap[west]
Requirements: <br/>
<ol>
<li>1. color values known </li>
<li>2. picture scale known </li>
<li>3. load as pixelmatrix </li>
</ol>
@snapend
```

That's fine. But you can still save a bit of the ceremony in your markdown, for example:

```
@snap[west]
Requirements: <br/>
@ol[](false)
- color values known
- picture scale known
- load as pixelmatrix
@olend
@snapend
```

If you like that approach I recommend you check out [markdown shortcuts](https://gitpitch.com/docs/markdown-features/shortcuts/) and [list fragments](https://gitpitch.com/docs/markdown-features/fragments#7-static-lists-with-fragments-disabled) in the docs.

**Comment by Twonki** [comment]
Thank you very much for your extensive Feedback!

Removing the intendations worked! 

There are two main reasons I use a lot of html: 
* First I had some problems organizing my items expecially when i'm @ Snapping them somewhere. 
* Second there are more frameworks for presentations out there, which often support html. Doing my code like that enables me to just change some syntax while keeping most of it. 

Removing the in-line styles is still a to do :P
