### ISSUE TITLE
Code block background too light for simple/white themes

### ISSUE THREAD

**Issue by fonnesbeck** [gitpitch/gitpitch#228]
Under the white and simple themes, the background for code blocks is white and the code itself is primarily light grey, which results in a low-contrast slide that is hard to read (it looks even worse on a projector):

![image](https://user-images.githubusercontent.com/81476/49595632-6c039080-f946-11e8-9404-7f2599ff9b3d.png)

Perhaps the themes should be tweaked to make this better by default, but in the meantime is there an easy setting to change this?

**Comment by gitpitch** [comment]
The background for a code block is independent of the fixed theme. It is determined by (1) the [code highlight setting](https://gitpitch.com/docs/settings/highlight/) and optionally by [custom css](https://gitpitch.com/docs/themes/custom/) activated for your presentation.

You did not mentioned what if any custom css you are using, or if your presentation is based on [The Template](https://gitpitch.com/docs/the-template/).

If you are using the template, then the background setting is disabled by the template's custom css. You will find the following style override in the `template/css/PITCHME.css` file:

```css
.hljs {
  background: none;
}
```

In order to re-activate the default background settings for your chosen [code highlight setting](https://gitpitch.com/docs/settings/highlight/) you would need to comment out this *template-specific style* rule.

If all of this does not help you resolve your problem then please share a link to a sample presentation that demonstrates the problem you reported and I will investigate further.

**Comment by fonnesbeck** [comment]
So, if I go in and set the highlight to Monokai, it gets even worse, with no background color -- I would expect a dark background with Monokai selected:

![image](https://user-images.githubusercontent.com/81476/49597424-660fae80-f94a-11e8-9f3a-400d51ac08f4.png)

Here is the offending slide:

https://gitpitch.com/fonnesbeck/neurips_2018_talk#/5

**Comment by gitpitch** [comment]
As noted earlier, if you are building your presentation on [The Template](https://gitpitch.com/docs/the-template) then you inherit by default the default template CSS. And the template defines the following default style rule that impacts code blocks:

```
.hljs {
  background: none;
}
```

You will find that style rule definition in the `template/css/PITCHME.css` file in your repository.

To override this default - and see the default backgrounds that you are expecting - you need to comment out this default style rule in the `PITCHME.css` file in your repository.

**Comment by fonnesbeck** [comment]
I see what you're saying now, sorry. Closing this issue,

**Comment by gitpitch** [comment]
> I see what you're saying now, sorry. 

No worries. It sounds like you now have what you need. But if not, just let me know and we can dig deeper.
