### ISSUE TITLE
Image not appearing in PDF export

### ISSUE THREAD

**Issue by fonnesbeck** [gitpitch/gitpitch#229]
Exporting my talk to a PDF results in a nearly-perfect deck of slides, except for one image, on the 12th slide:

https://gitpitch.com/fonnesbeck/neurips_2018_talk#/11

It is a local image, and appears fine on the web, but does not get rendered in the PDF. I have tried it both as a background image and as a snap layout, with the same results.

**Comment by gitpitch** [comment]
Hi Chris. Nice looking presentation. So invariably when an image does not appear in PDF output it is because the image overflows the edges of your slide. Most frequently due to a mismatch in the aspect ratio of your source image and the aspect ratio of the slide. If you are interested you can read more about this issue [here](https://github.com/gitpitch/gitpitch/issues/170) and [here](https://github.com/gitpitch/gitpitch/issues/167).

I suggest you make a small tweak to *params* on *image-delimiter* in your current `PITCHME.md` replacing this:

```
---?image=assets/img/pymc_fortran.png&size=auto 100%
```

With this:

```
---?image=assets/img/pymc_fortran.png&size=auto 90%
``` 

This will cause your image to display marginally smaller on the slide. But should fix the PDF printing issue. If you try it out let me know how it goes.

As an aside, looking at your presentation I noticed that the `logo` setting in your **PITCHME.yaml** file is pointing at a file that does not exist in your repo. There is a `jpg` file of the same name. But that jpg image is not suitable to be a logo as it has very large dimensions and is mostly whitespace which will not function well as an icon/logo.

**Comment by fonnesbeck** [comment]
Yes, that did the trick. Thanks for the advice.
