### ISSUE TITLE
highlightjs 9.13.1 css fails to load in online mode

### ISSUE THREAD

**Issue by sammoorhouse** [gitpitch/gitpitch#239]
In a presentation with code syntax highlighting (e.g. https://gitpitch.com/glblcd/pyladies-2019-02) syntax highlighting fails with the following console error:

(Chrome MacOS Version 72.0.3626.109 (Official Build) (64-bit))
Refused to apply style from 'https://gitpitch.com/assets/libs/highlight.js/9.13.1/Default.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

(Safari Version 12.0.1 (14606.2.104.1.1))

Failed to load resource: the server responded with a status of 404 (Not Found)

Highlighting works fine in offline mode. If I try to load the file manually in either browser I get a 404 error.

**Comment by gitpitch** [comment]
Hi Sam, it looks like the problem is with the value you have set on the `highlight` property in the `PITCHME.yaml` for your presentation.

See the [highlight setting guide](https://gitpitch.com/docs/settings/highlight), in particular, this note:

> All highlight.js style names specified on the highlight setting must be in lower-case only.

 So try changing your current setting value from:

```
highlight: Default
```

To:

```
highlight: default
```

And let me know if that solves your problem.

**Comment by gitpitch** [comment]
Quick update. I've just pushed a patch - now live on gitpitch.com - that makes the value on the `highlight` setting case-insensitive. So now `Default`, `default`, or any case-variation on that word will result in the correct syntax highlighting for code on your slides.
