### ISSUE TITLE
BAD REQUEST opening GitPitch Desktop in Chromium

### ISSUE THREAD

**Issue by flokno** [gitpitch/gitpitch#248]
When I run gitpitch Desktop on chromium, I get a `Bad Request` error with
`For request 'GET /' [HTTP header is larger than 8192 bytes.]`

It doesn't occur on Firefox, though.

![Screenshot_20190402_112443](https://user-images.githubusercontent.com/28858706/55391917-8dfad180-553a-11e9-9fbd-4c74fa4ae370.png)

**Comment by gitpitch** [comment]
Hi Florian, while Chromium is not an officially supported browser for GitPitch, given its close relationship with Chrome browser I would still expect it to work. And having tested locally, it did work.

_So I suspect the issue is specific to your environment._ 

Just FYI, here is GitPitch Desktop open in the Chromium browser on my OSX desktop:

<img width="1440" alt="gitpitch-desktop-chromium-1" src="https://user-images.githubusercontent.com/19169584/55399920-a5f04680-5576-11e9-9244-2bda50f5823e.png">

And here is a sample GitPitch slide deck open inside GitPitch Desktop in that browser:

<img width="1440" alt="gitpitch-desktop-chromium-2" src="https://user-images.githubusercontent.com/19169584/55399941-b56f8f80-5576-11e9-920f-12ab436fc91e.png">

And here are the version details for my local installation of Chromium:

<img width="1440" alt="gitpitch-desktop-chromium-3" src="https://user-images.githubusercontent.com/19169584/55400045-f9629480-5576-11e9-9e54-a8d100839e09.png">

You didn't mention Chromium version or your desktop environment in your description but as noted above, I suspect the problem is in your local setup.

**Comment by flokno** [comment]
Thanks David, indeed simply clearing the cache helped out.
Thanks for checking!
