### ISSUE TITLE
Code blocks not working as intended?

### ISSUE THREAD

**Issue by menzzana** [gitpitch/gitpitch#252]
Hi

Has something changed when displaying codeblocks?
My presentation looked ok, but after last week, presentation where I have included code blocks are faulty. Instead of displaying a black background for the code only, the whole page is black and the fonts are wrong.

See example on my test presentation which I use to highlight features. https://github.com/menzzana/gitpitch-test/blob/master/PITCHME.md which is displayed at https://gitpitch.com/menzzana/gitpitch-test

The slides 4-5 has a black background as I have code blocks on them?

I can show you more examples as even presentations I have not touched in a while has changed in that aspect.

Is this a bug or has something changed that I have missed?

Best regards

**Comment by gitpitch** [comment]
Hi @menzzana,

> Is this a bug or has something changed that I have missed?

It is not a bug. It looks like you missed the announcement about [the new Theme Template](https://gitpitch.com/docs/themes/default). The *Theme Template* has become the new default theme. So if a presentation has not explicitly activated a named theme it will now be rendered using the new default theme.

I can see the presentation in the repo you linked to does not specify a `PITCHME.yaml` file so it is definitely being rendered using the default. And as noted, that default has changed.

If you want your deck to look the way it used to then as you need to do is set the following property in a `PITCHME.yaml` for the deck:

```
theme :  white
```

The `white` theme was the old default so that is the theme that used to be used to render your deck.

But I recommend you take this opportunity to look into the new [Theme Template Guide](https://gitpitch.com/docs/themes/default). It's has numerous in-built improvements. Including automatic blending of code blocks into the slide background. Which explains why your slides with code blocks are now black. If you don't want black slides just changes the [highlight setting](https://gitpitch.com/docs/settings/highlight) in your `PITCHME.yaml` to chose a code highlight style and background color that you do like.

As a final tip, if you want to keep informed about GitPitch news and feature updates, follow the GitPitch Twitter account [here](https://twitter.com/gitpitch).

**Comment by menzzana** [comment]
Hi

Yes, that was it and I missed. Sorry for that.
My other presentations do use a yaml file, but have not defined this tag.

Anyway, thank you for a speedy response and I will check out the new template guide as it does look interesting.

Have a nice summer....

**Comment by gitpitch** [comment]
Glad you now have what you need. And thanks for the summer wishes. You too. All the best, David.
