### ISSUE TITLE
Code support

### ISSUE THREAD

**Issue by mrava87** [gitpitch/gitpitch#254]
Hello,
I have made some slides with GitPitch and until yesterday I could see my code snippets, today I just get a message instead of them saying ‘Upgrade to pro...’, does that mean that code features have disappeared from the free version? 

I understand that some new fancy features can only be accessed by pro version but you should try to avoid backward incompatibility of older slides by changing something that was free into something that requires a pro version. 

Looking forward to hearing from you.

**Comment by gitpitch** [comment]
Hi Matteo, 

Thanks for getting in touch. I have answers to your questions inline.

> does that mean that code features have disappeared from the free version?

No. The **Pro Code Widget** was never part of the free version so it was never a feature for free users. Per the [Pro Code Widget Guide](https://gitpitch.com/docs/code-features/pro-code-widgets):

> GitPitch Pro + Lite subscriptions activate powerful Pro syntax shortcuts supported by PITCHME.md markdown that can be used to generate rich visual components - aka. widgets - on any slide. The Code Widget and GitHub GIST Widget support a number of powerful extensions beyond standard code presenting. 

The **Pro Code Widget** as the name implies was-and-is a *subscriber-only* feature.

> I have made some slides with GitPitch and until yesterday I could see my code snippets, today I just get a message instead of them saying ‘Upgrade to pro...

What you describe can be explained by an internal experiment just ended. I have been running some experimental code on gitpitch.com this past month. One consequence of that experiment was that a free user would see code rendered (rather than the pro-only warning) if they used the `@code` widget. But that was a side-effect of the experiment. Not a change in policy. The **Pro Code Widget** feature was never documented or publicized as a free feature.

> ...but you should try to avoid backward incompatibility of older slides by changing something that was free into something that requires a pro version.

I hope it is clear to you now that I have not done this. I do appreciate that you feel inconvenienced by your recent experience. That's unfortunate. That said, if you are a fan of the `@code` widget feature you can always upgrade from the free to a paid plan to continue enjoying the feature. And if not, GitPitch offers numerous other ways to render code on your slides that are available to everyone, including:

- [Fenced Code Blocks](https://gitpitch.com/docs/code-features/fenced-blocks)
- [Source Code Delimiters](https://gitpitch.com/docs/code-features/source-files)
- [GIST Code Delimiters](https://gitpitch.com/docs/code-features/gists)

All the best,
David

**Comment by mrava87** [comment]
Hi  David,
thanks a lot for quick reply. 

I have not used gitpitch for some months and when I started again last week and resigned for the lite version right now, I used the **Pro Code Widget** and didn't realize it was pro (my fault): things worked fine offline and online (I guess because of your experiment) and so I didn't pay too much attention until this morning things changed.

Will go for Fenced for the moment, thanks a lot for the feedback :)

**Comment by gitpitch** [comment]
> thanks a lot for quick reply.

You're very welcome.

> things worked fine offline and online (I guess because of your experiment)...

Yes, some of what you experienced was partly because of the experiment, but perhaps not all. Let me explain by first summarizing the differences between the GitPitch plans:

1. The **Free Plan** lets you use all FREE features in the cloud.

2. The **Lite Plan** lets you use all PRO features on the desktop. And all FREE features in the cloud.

3. The **Pro Plan** lets you use all PRO features on the desktop. And all PRO feature in the cloud.

You are a Lite user. So as a Lite user you can use all of the PRO features - including the `@code` widget - on your desktop. But if you want to publish and share that deck on gitpitch.com then you would need to upgrade from your Lite plan to a Pro plan in order to activate those Pro features everywhere: desktop and cloud.

Just fyi, you can upgrade from Lite to Pro with just one-click on your GitPitch profile page. Login [here](https://gitpitch.com).

I hope this helps. If not, please feel free to respond here. Or drop me an email directly and we can discuss further. Thanks, David.

**Comment by mrava87** [comment]
Thanks :) 

Yep, I think  I got the plans right, but the fact it worked also online made me think (by mistake) that this was a free feature ;)

**Comment by mrava87** [comment]
One last, slightly related question:
can i have a fenced code block inside a snap e.g.:

```
@snap[south span-60 text-08]
\```
some code
\```
@snapend
```
(without \ inside the code snippet).

It worked fine with ``@code`` inside but I don't seem to get it work with the fenced code block

**Comment by gitpitch** [comment]
> can i have a fenced code block inside a snap...

No, you can not. But you can try using HTML tags like this:

```
@snap[south span-60 text-08]

<pre><code>
...your code goes here...
</code></pre>

@snapend
```
