### ISSUE TITLE
Code: Reduce Whitespace

### ISSUE THREAD

**Issue by martindsouza** [gitpitch/gitpitch#262]
I have a code block that is ~30 lines long. I'd like to be able to maximize the space on the screen so most of the code is visible. I've loaded the code using the following lines:

```
---?code=src/data_emp.sql&lang=sql zoom-04 code-power

...
```
and
```
---
@code[sql code-power zoom-04](src/data_emp.sql)

...
```

I thought that `code-power` may maximize the space on the screen. Instead I have some huge whitespaces above and below the code:

![Snip20190901_19](https://user-images.githubusercontent.com/2925726/64082744-286d6580-ccd1-11e9-8e75-d31b8907738c.png)

Even if a Step-and-zoom is used there's still a lot of whitespace above and below code:

![image](https://user-images.githubusercontent.com/2925726/64082751-4b981500-ccd1-11e9-9a6d-0b2c180a935d.png)

Is their a way to reduce/define the `margin` or `padding` around code blocks?

**Comment by gitpitch** [comment]
> Is their a way to reduce/define the margin or padding around code blocks?

The space around the code block on your slide is not caused by margins or padding, it is determined by a `code` style rule set in the underlying theme for your slide deck. For example, the following shows the default style rule for code blocks for slide decks using the theme template:

```css
.reveal pre code {
  max-height: 60vh !important;
}

@@media (device-width: 100vw) and (device-height: 100vh) {
  .reveal pre code {
    max-height: 50vh !important;
  }
}
```

You could adjust the `max-height` property value using custom CSS.  For example,  you could increase this value and consequently increase the space available to code blocks on your slide.

**But I do not recommend it.** The default value has been tested to work across browsers, in standard and full-screen mode, and at different resolutions. If you adjust this value to make it look "better" on your screen, expect rendering problems for you audience if you share your deck.

If you have a live presentation to give and you have access to the display device to test your deck ahead of time, you could create a display specific version of your deck that optimizes for that display.
 
But as a rule of thumb, I recommend that you stick with the defaults.

**Comment by martindsouza** [comment]
@gitpitch Thanks for the feedback. Will leave things alone then.
