### ISSUE TITLE
UML diagram height

### ISSUE THREAD

**Issue by martindsouza** [gitpitch/gitpitch#263]
I have the following in a `.puml` file:

```puml
@startuml
start
:development;
:build release;
:release;
:tag code;
:post-release;
stop
@enduml
```

Using the example from the [@uml docs](https://gitpitch.com/docs/rich-media-features/uml-diagrams/#uml-widget-for-diagrams) my slide is:

```md
--- 
@snap[west span-60]
@code[uml rawcode zoom-15](/src/uml/theory-sprint.puml)
@snapend

@snap[east span-40]
@uml[span-100 bg-white](/src/uml/theory-sprint.puml)
@snapend

@snap[south-west span-100]
@[1,6](Start with opening and closing PlantUML delimiters.)
@[2,3](Declare participants, actors, boundaries, etc.)
@[4,5](Then define the messages between participants.).
@snapend
```

The results show the puml diagram that isn't scaled to fit the screen:

![image](https://user-images.githubusercontent.com/2925726/64135251-9bdfa780-cda3-11e9-8d05-65fb6d2c0e41.png)

When inspect the image and render in a new tab I can see that it does have the full uml content:

![image](https://user-images.githubusercontent.com/2925726/64135259-c29dde00-cda3-11e9-9962-94e65e2c6d28.png)

What can I do to scale the resulting uml diagram?

**Comment by gitpitch** [comment]
> What can I do to scale the resulting uml diagram?

@martindsouza You are already scaling the resulting image by using the `span-40` on your `@snap[east span-40]` tag. But you are not scaling enough because your image is very-narrow-and-very-tall. So scaling down the width is still resulting in a very tall image. Which is a poor fit for for a slide with a 16:9 aspect ratio. 

But if you use a smaller span value, perhaps `span-20` or even `span-5` the image may fit, but you are likely going to end up with a very small image.

So you might want to reconsider the design of your slide and your diagram. Take a look at recommendation detailed in the [UML Diagrams Layout Controls](https://gitpitch.com/docs/rich-media-features/uml-diagrams/#uml-diagrams-layout-controls) section in the docs. It addresses this exact scenario. And offers an alternative.

**Comment by martindsouza** [comment]
@gitpitch thanks for response. For others: I ended up changing the spans to:

```
@snap[west span-80]
@code[uml rawcode zoom-15](/src/uml/theory-sprint.puml)
@snapend

@snap[east span-20]
@uml[span-100 bg-white](/src/uml/theory-sprint.puml)
@snapend
```

And result is: 

![image](https://user-images.githubusercontent.com/2925726/64177461-c6217b80-ce1c-11e9-8697-1b100b8eb5a9.png)
