### ISSUE TITLE
XML snippet not scrollable in code widget

### ISSUE THREAD

**Issue by sennierer** [gitpitch/gitpitch#264]
Hi,

I have a pretty big XML file that has long lines. I use fragments and the zoom feature to click through the file and show the interesting bits, but I would also like to scroll through the file. However, though I havent set code-noscroll I cant scroll through the file.

This is my md:

@code\[xml code-blend code-max\]\(data/FILE.xml\)

@snap[south span-100]
@[10-19](Void metadata)
@[190-195]
@\[104-107\]\(appellation\)
@[206-211]
@[138-143](date appellation)
@snapend

Am I doing something wrong?

**Comment by gitpitch** [comment]
Hi Matthias,

I doubt you are doing anything wrong. But I suspect you have activated the [theme template](https://gitpitch.com/docs/themes/default) for your slide deck. Is that right?

The default behavior for slide decks using the *theme template* is for *overflow* to be disabled by default for code blocks within those decks. This is the default because in most cases it makes for much nicer looking slides (no scrollbars are visible).

But you can override this default using a small snippet of [custom CSS](https://gitpitch.com/docs/themes/custom) for your deck. If you want to override the default behavior *globally* for every slide in your deck you should activate the following CSS snippet:

```css
.reveal pre code { overflow: auto; }
```

By default, this property is set to *hidden*. So by setting it to *auto* you should be able to scroll through your big XML file. 

But we can do better. If you want to activate scrollbars for just this big XML file but leave the behavior of all other code slides unchanged, you can first declare a custom CSS class as follows:

```css
.code-scrollable { overflow: auto !important; }
```

And then you can activate this custom style on the specific code widget, like this:

```
@code[xml code-blend code-max code-scrollable](data/FILE.xml)
```

Hopefully one of these approaches -  the global solution or slide specific solution - will give you what you need.

And if I'm wrong and you are using one of the [old deprecated themes](https://gitpitch.com/docs/themes/default#deprecated-themes-notice) for you deck let me know and we can dig deeper.

**Comment by sennierer** [comment]
Perfect! The custom snippet did the trick!
Thanks for the very fast reply!

**Comment by gitpitch** [comment]
> Perfect! The custom snippet did the trick!

Great. Glad you got what you need. Cheers, David.
