### ISSUE TITLE
Link to download file

### ISSUE THREAD

**Issue by martindsouza** [gitpitch/gitpitch#267]
In my `assets` folder I have a file I want users to be able to download if they like (it's a demo file):

![image](https://user-images.githubusercontent.com/2925726/64616926-b6fd7900-d39a-11e9-8251-5ef809930da7.png)

My slide contents:

```
---?color=black

# Demo

@snap[south]
[demo-file](assets/src/demo/demo.sh)
@snapend
```

When I click on the `demo-file` link it just brings me back to `http://localhost:9090/gitpitch/desktop#/` rather than download the file.

How can I reference a "local" file for download?

**Comment by gitpitch** [comment]
> How can I reference a "local" file for download?

If the file is found within the same repository as the slide deck, then you can use the `@gitlink` markdown widget. See the [docs](https://gitpitch.com/docs/markdown-features/widgets). This link will only be activated when your deck is pushed to the cloud and served from [gitpitch.com](https://gitpitch.com). When working locally with GitPitch Desktop there is no Git repo context so the `@gitlink` widget links to `#`. 

Otherwise, you could specify an absolute URL as long as the file you are sharing is hosted by some external service.

**Comment by martindsouza** [comment]
Thanks. `@gitlink` docs: https://gitpitch.com/docs/markdown-features/widgets/#git-repo-link-widget
