### ISSUE TITLE
DesktopPro error in embedded GIF rendering as image in PDF and PPTX

### ISSUE THREAD

**Issue by tyson-swetnam** [gitpitch/gitpitch#271]
I have a presentation with A LOT of GIF images pulling from Giphy. 

https://github.com/tyson-swetnam/agic-presentation

<img width="1440" alt="Screen Shot 2019-09-28 at 10 32 38 AM" src="https://user-images.githubusercontent.com/11527041/65820229-6cbe2980-e1db-11e9-93c0-8aa3efacbcb4.png">
<img width="1183" alt="Screen Shot 2019-09-28 at 10 33 02 AM" src="https://user-images.githubusercontent.com/11527041/65820230-6cbe2980-e1db-11e9-8299-f6f2b2096130.png">

In Docker Desktop Pro as either PDF or PPTX, the wrong GIF thumb is rendered for all of the GIFs (ironically, it is a picture of a dumpster fire).

**Comment by gitpitch** [comment]
Hi Tyson,

I've just been looking over your deck. No kidding, a LOT OF GIFs. But I dug into your `PITCHME.md` and I see the likely cause of your printing problem. 

Your deck loads a huge amount of image data (~70Mb gif, jpg, png, svg) over the network from almost 40 different services and sites around the Web. And it is the lag time associated with loading all of this data that is preventing a clean print.

If you want to print this deck you are going to have make your image dependencies local to your slide deck. Either for your main deck. Or create a version of the deck just for printing. In either case, adopting this recommendation means these files will be loaded from disk rather than from the network when printing. And this change should allow you to generate clean PDF and PPTX.

Remember, if you do make your image dependencies local make sure to *size-optimize* the files per the [Image Guide Recommendations](https://gitpitch.com/docs/image-features/size-limits).
