### ISSUE TITLE
Incorrect centered image when is located in north-east position

### ISSUE THREAD

**Issue by Burgyn** [gitpitch/gitpitch#276]
Hi,

I have no idea what I'm doing wrong. When I try to place the picture in the upper right corner, it is incorrect centered.

![image](https://user-images.githubusercontent.com/5930822/68571760-0a0baf00-0464-11ea-8856-71fcbdf46575.png)
https://gitpitch.com/burgyn/presentations/master?p=LayoutTest

see my repo: https://github.com/Burgyn/Presentations/tree/master/LayoutTest

Thank you in advance for your advice.

Info:
OS: Windows 10
Browser: Opera

**Comment by gitpitch** [comment]
@Burgyn the issue here appears to be the aspect ratio you are using to view your slide deck in your browser.

The standard aspect ratio for a GitPitch slide deck is 16:9. But looking at your screenshot it looks like you have sized your browser to be very wide (left-to-right) but also very short (top-to-bottom). As a consequence of this layout for your browser the positioning of your image looks off.

To test my theory you should try viewing your slide deck in full-screen mode. To open full-screen mode, press the F key. If you are viewing your slide deck on a standard laptop or desktop your full-screen aspect ratio will be 16:9. So you should see the content on your slides rendered as you expect. Do you?

If you try this test let me know how it goes. Cheers, David.

**Comment by Burgyn** [comment]
Hi, thanks for your advise.
Unfortunately it didn't help. My screen resolution (in fullscreen mode) is 1920x1080.

I try change question.
How can I correctly center image in each of six positions?
When I trying it, images aren't centered properly.

Please see my example:
https://gitpitch.com/burgyn/presentations/master?p=LayoutTest

![image](https://user-images.githubusercontent.com/5930822/69118595-583c3600-0a94-11ea-97bd-8d66be4759b4.png)

Thank you in advance for your advice.

**Comment by gitpitch** [comment]
> How can I correctly center image in each of six positions?

It appears the main problem here is a mismatch of expectations. Your background image colored boxes do not correspond to the snap-layouts grid compass positions - they do not account for margins, padding, etc. So centering the sample image inside each of your colored boxes is not possible.

For testing purposes, if you are trying to see what region of your slide maps to a specific snap-region then instead of using a colored background image you are better activating a [background color property](https://gitpitch.com/docs/themes/css-utility-styles/#background-color-styles) on the snap tag. For example, `@snap[north-west span-33 bg-yellow]` That will show you the exact region on your slide the snap-region maps to. If you adjust the *span-xx* property value and/or add content within the snap tags you will see the size of that region changes accordingly.

Here are the default alignments for the snap-grid:

- north-west, west, and south-west are *text-left* aligned by default
- north, midpoint, and  south are *text-center* aligned by default
- north-east, east, and south-east are *text-right* aligned by default

If you want to horizontally center your content in each snap-region on your slide (regardless of the position on the grid) simply activate the [text-center](https://gitpitch.com/docs/themes/css-utility-styles/#text-alignment-styles) property on each snap tag.

**Comment by Burgyn** [comment]
Hi,
thanks for your clear explanation.
