### ISSUE TITLE
How to get title and then background image sized down

### ISSUE THREAD

**Issue by elect86** [gitpitch/gitpitch#280]
As titled, this is what I'd like to have: https://gitpitch.com/gitpitch/feature-demo/customize-image-size#/3

but this is what I get instead locally if I use the very same code: https://imgur.com/WIFdk9o

**Comment by gitpitch** [comment]
Hi Giuseppe, if you look in the `PITCHME.yaml` file for the Image Magic feature demo slide deck you will see that the [automatic layout policy](https://gitpitch.com/docs/settings/layout) setting for slide content in that deck has been set to `top`.

And while you did not share the `PITCHME.yaml` for your deck I suspect you are using the *default* auto-layout policy. That default is `center`.

If I'm right then you have two options:

1. Set the `layout` setting to `top` in your `PITCHME.yaml`
2. OR use [snap layouts](https://gitpitch.com/docs/layout-features/snap-layouts/) to *snap* your title text into the *north* grid position on your slide.

If you try these out let me know how it goes. Cheers, David.

**Comment by elect86** [comment]
This is my [`PITCHME.yaml`](https://gist.github.com/elect86/49a3eac151f6ae48ca08757d0a8c2008), which I guess it's wrong, because I have twice all the parameters (setting the first `layout` to `top` didnt work indeed, the second made the trick)

**Comment by gitpitch** [comment]
Hi again. If you look carefully you will see that you have the `layout` setting set three times in your `PITCHME.yaml` file. It is always the last occurrence of any setting that is the value that is activated for your deck.

Btw, the reason for the third (and final) layout setting in that file is because you must have opened the [Theme Builder](https://gitpitch.com/docs/themes/default). And the Theme Builder will write to this file is you make changes. I recommend you read [this note](https://gitpitch.com/docs/themes/default/#export--share-theme-settings) about making Theme Builder settings final.

**Comment by elect86** [comment]
Ok, thanks, I'll remove the tags then

Shall I also delete all the previous, apparently useless, settings? In order to leave only the Theme Builder settings?

**Comment by gitpitch** [comment]
> Shall I also delete all the previous, apparently useless, settings? In order to leave only the Theme Builder settings?

The Theme Builder only overrides theme related settings. I see other settings in your `PITCHME.yaml` file for things like `footnote`, `twitter-card`, etc. So you can remove duplicate settings, sure. But I advise doing so with a little bit of care so you do not accidentally delete settings you really would prefer to keep.
