### ISSUE TITLE
Poor code highlighting for java/kotlin

### ISSUE THREAD

**Issue by elect86** [gitpitch/gitpitch#281]
As titled, the gitpitch code highlighting for java and kotlin is a little [poor](https://imgur.com/vHNIKTu) compared to GH markdown, where I get different colors also for `=` and constants, to say ([example](https://github.com/kotlin-graphics/gln/blob/master/README.md))

Any way may I improve this?

**Comment by gitpitch** [comment]
> Any way may I improve this?

Your sample block does look a little dull so I tried another sample block of code that rendered as follows:

![kotlin-highlighting](https://user-images.githubusercontent.com/19169584/73073608-4474dc00-3eea-11ea-9f6c-37cbdb703f89.png)

My sample block of Kotlin code shows a wide range of distinct highlights so I suspect there is something about your specific code block that is preventing the syntax highlighting being fully activated. I also tried to set the [language hint](https://gitpitch.com/docs/code-features/fenced-blocks/#the-importance-of-code-language-hints) to a number of other values such as `php`, `javascript`, etc just to test and in every case the block rendered the same, without much distinctive highlighting. So again this leads me to believe that the issue is specific to something in this block.

All that said, I do not currently have a way to improve this for your block of sample code.

**Comment by elect86** [comment]
Could you try `=` and constants?

**Comment by gitpitch** [comment]
Sure, I tried your original code snippet. And I got the same result you did, Kotlin constants are not receiving special highlighting in GitPitch. For example, on the left is a Java block and on the right is Kotlin:

![java-kotline-constants](https://user-images.githubusercontent.com/19169584/73122080-20310200-3fb3-11ea-8c24-52db072e276e.png)

While my sample is using the `github` style from the [highlight.js library](https://highlightjs.org/) in it's `PITCHME.yaml` settings the rendering is not identical to what you are seeing on GitHub.

**Comment by elect86** [comment]
> While my sample is using the github style from the highlight.js library in it's PITCHME.yaml settings the rendering is not identical to what you are seeing on GitHub.

Is this intended behavior?

**Comment by gitpitch** [comment]
> Is this intended behavior?

I would say it is the expected behavior. GitPitch code syntax highlighting is powered by the [highlight.js library](https://highlightjs.org/). It is not powered by the library used by GitHub itself. So GitPitch using *highlight.js* can and does approximate GitHub styles by offering the `github` and `github-gist` options. But these styles may not match the GitHub styles perfectly in all cases. And Kotlin constants is clearly one such case.

I do keep up to date with `highlight.js` releases. So if some future release adds support for Kotlin constant highlighting then GitPitch users will automatically benefit from that change if/when it occurs.
