### ISSUE TITLE
Fonts rendering differently in fullscreen mode in different browsers

### ISSUE THREAD

**Issue by Sean-P-Carey** [gitpitch/gitpitch#289]
My slide show renders differently in fullscreen mode depending on the browser being used. 
Examples in pictures. 

<img width="1674" alt="safari" src="https://user-images.githubusercontent.com/60041971/75607819-d1521d00-5ac8-11ea-85c2-8cdb1031e028.png">
<img width="1677" alt="firefox" src="https://user-images.githubusercontent.com/60041971/75607821-d4e5a400-5ac8-11ea-9e3d-11ed3f1ba48f.png">

[Slide Deck](https://gitpitch.com/SeanCarey/Regis-MSDS-Practicum-1?grs=gitlab#/)

[repo](https://gitlab.com/SeanCarey/Regis-MSDS-Practicum-1)

**Comment by gitpitch** [comment]
Hi Sean, thanks for reporting this issue. The underlying cause here is the small difference that can result when calculating spacing, padding, and margins across browsers. In most cases, the slight size variations across browsers are not detectable. But when you brush up against an edge case *(such as your sample slide)* the rendering differences can be readily apparent.

On your sample slide the "Exploratory Analysis" H2 text being rendered coincidentally fills the entire *span-100* width of the slide. There is basically no *wiggle room* within the *southern* snap-region on your slide for small rendering differences across browsers. Hence the issue that you have reported.

The simplest and recommended solution is to make *wiggle room* for your text. By scaling down the size of *headline* text for this deck. Headline text references to H1 and H2 text. To scale down the size of headline text you can simply tweak the theme settings in your *PITCHME.yaml* file.

Probably the simplest way to tweak these theme settings is to use the [Theme Builder](https://gitpitch.com/docs/themes/default). But to help you clearly understand what I'm doing here let me explain here how this tweak can be made manually.

The current **theme-headline** property setting in your *PITCHME.yaml* file is as follows:

```yaml
theme-headline   : [ "Montserrat", "#FBD95E", "none", "#FFFFFF", "100", "120", "15" ]
```
You could adjust this property as follows:

```yaml
theme-headline   : [ "Montserrat", "#FBD95E", "none", "#FFFFFF", "96", "120", "15" ]
```
Note the *scale* property value has been reduced from *100* to *96* percent. With this change all H1 and H2 headline content in your slide deck will be rendered slightly smaller than the default size, specifically at *96%* of that default size. And that adjustment is all that is needed to introduce the necessary *wiggle room* for your current text. And with that wiggle room in place, you should see consistent rendering across all browsers.

If you try this out let me know how it goes. Cheers, David.

**Comment by gitpitch** [comment]
Btw, if you don't want to scale the size of headline content for your deck another solution is to simply choose a new font for headline content. For example you could try the following **theme-headline** settings:

```yaml
theme-headline   : [ "Ubuntu", "#FBD95E", "none", "#FFFFFF", "96", "120", "15" ]
```

Here I substituted *Ubuntu* for *Montserrat*. As Ubuntu is a more compact font it allows your current text to fit on your sample slide with plenty of *wiggle room* for any cross browser size differences.

This is just FYI. You can use whatever approach you prefer.

**Comment by Sean-P-Carey** [comment]
Thank you very much for your quick response. Scaling the size of my headline to 94 did the trick. Thank you.

**Comment by gitpitch** [comment]
Ok. Glad that gave you what you need.
