### ISSUE TITLE
Ability to mix inline image with text, list, headers etc

### ISSUE THREAD

**Issue by bwplotka** [gitpitch/gitpitch#305]
**Describe the bug**
Hi!

I would love to use inline images with a custom options in more places like text, lists, headers etc. Unfortunately, this does not work currently, the custom `tags` in `[]` as described [here](https://gitpitch.com/docs/image-features/image-manipulation/#image-sizing) are ignored. It would be nice if this would work :hugs: 

BTW Is the proper place for support issues / features? I am trialing the product and so far it's amazing, but there are always some things to be improved, if you want feedback (: 

**To Reproduce**

Following snipped reproduces this:

```markdown
![width=50](some/image.png) <!-- This works perfectly. --->

some text ![width=50](some/image.png)  <!-- Does not work (width ignored).  --->

# ![width=50](some/image.png)  <!-- Does not work (width ignored).  --->

# some text ![width=50](some/image.png)  <!-- Does not work (width ignored).  --->

* ![width=50](some/large/image.png)  <!-- Does not work (width ignored).  --->

* some text ![width=50](some/large/image.png)  <!-- Does not work (width ignored).  --->

@ul[](false)
* ![width=50](some/large/image.png)  <!-- Does not work (width ignored).  --->
@ulend
```

**Expected behavior**
Image  tag e.g `width` will be applied to the image.

**Browser (please complete the following information):**
 - Chrome

**Operating System (please complete the following information):**
 - Linux

**Comment by bwplotka** [comment]
I used `img` with some custom CSS as a workaround here: https://github.com/bwplotka/my/blob/optimizing-clouds/slides/common/whoami-go/PITCHME.md

**Comment by gitpitch** [comment]
Hi Bartlomiej, 

> I would love to use inline images with a custom options in more places like text, lists, headers etc. Unfortunately, this does not work currently, the custom tags in [] as described here are ignored. It would be nice if this would work 🤗

Agreed :) As you have found the markdown image syntax won't work in these cases. And I was going to suggest as a workaround you could use a HTML `<img>` tag and activate the necessary  styles properties on that tag to give you what you need. But it seems you found that approach yourself. And for now that is the best and indeed only workaround.

To support this cleanly using GitPitch markdown syntax I think I would need to extend the set of [image manipulation properties](https://gitpitch.com/docs/image-features/image-manipulation/) to include a `display` property because in each of the examples you mentioned I think you would need to active an `inline` style on the image. It might nice to be able to simply activate `display: inline` as an additional property on the image. Something like this:

```
Passionated about Go ![width:80, display:inline](assets/images/gopherme.png)
```

Btw, this specific note is as much a reminder to myself as it is information for you. 

> BTW Is the proper place for support issues / features? I am trialing the product and so far it's amazing, but there are always some things to be improved, if you want feedback (:

Yes indeed, this is the proper place for bugs reports or feature requests. So thanks for the feedback. And I'll keep this issue thread open as a feature request and will update it once I have a chance to work the issue. Cheers, David.

**Comment by bwplotka** [comment]
Awesome!

I think something like  `![width:80, cssclass](assets/images/gopherme.png)` and some `inline` tag would be perfect yes (:

**Comment by gitpitch** [comment]
With the release of [GitPitch 4.0](https://twitter.com/gitpitch/status/1310868554296815618) you can now use [Grid Stacks](https://docs.gitpitch.com/#/grid-layouts/stacks) combined with [Grid Synchronization](https://docs.gitpitch.com/#/grid-layouts/stacks) to synchronize the display of text-based list content and stack based rich-media content including images, code, etc.

List and stack synchronization is now the recommended approach to display text and rich-media content simultaneously on any slide. Given the availability of these new features I won't be extending rich-media support directly within existing list syntax. Closing this RFE as implemented.
