### ISSUE TITLE
Consider more control on code snippets (embedding, more lines, font changes & background control)

### ISSUE THREAD

**Issue by bwplotka** [gitpitch/gitpitch#307]
:wave: 

Sorry, it's me again, this time I played with code pieces. Overall it works nicely if you have *only* the code on the slide and not many lines of it.

I think it's generally good practice, but I am preparing a presentation on Programming language meetup (it's [this Wednesday](https://www.meetup.com/LondonGophers/events/270419925/) ;p) and because the meetup is virtual I think it's a valid case to make the slide more buffy and show more.

You can see my current try here: https://gitpitch.com/bwplotka/my/optimizing-clouds?p=slides/optimizing-go-for-clouds-go-meetup#/5

So open questions from my side:

* I tried to add more lines than 23, but I could not find any control for this in docs, is there any way I can poke `@code` to show more lines (`zoom+20` ;p)
* I would love to change font size to embed this code within some other snap title etc. `text-xxx` does not work. I can fix this with custom CSS, but maybe there is more native way?
* I see `lines=22-24` in Code Filters section for `---code` example. Is there a way to use similar for `@code` widget?
* Somehow background is not preserved - I think it makes sense to change the background of code snipped but why adjusting everything behind? Is there a way to control this? (: Especially when code is used as a fragment in mentioned slides you can see how it would be nicer (: 

Sorry for the extra traffic on those issues, and thanks for the quick responses so far. I think if nothing else, it might be good feedback for the future, most of those things I can hack with custom CSS  I guess. Just trying to make sure I don't miss some easy win here.

**Comment by bwplotka** [comment]
BTW on narrower window I can see 24 lines (:

**Comment by gitpitch** [comment]
> I tried to add more lines than 23, but I could not find any control for this in docs, is there any way I can poke @code to show more lines (zoom+20 ;p)

Take a look at the [Code Zoom Guide](https://gitpitch.com/docs/code-features/pro-code-zoom). Specifically the sections that discuss *zooming out* rather than *zooming in*. If you zoom out it will reduce the size of the code font and as a result you can show more lines of code on a single slide.

> I see lines=22-24 in Code Filters section for ---code example. Is there a way to use similar for @code widget?

Yes. Look at the [Code Filters Guide](https://gitpitch.com/docs/code-features/pro-code-filters/#code-slide-with-tags-filter). Specifically the example that demonstrates the [Code Tags Filter](https://gitpitch.com/docs/code-features/pro-code-filters/#code-slide-with-tags-filter). That exact same approach can be used on the *@code* widget to activate a lines filter. For example:

```
@code[elixir](src/demo.ex?lines=1,3-6,9)
```

> Somehow background is not preserved - I think it makes sense to change the background of code snipped but why adjusting everything behind? Is there a way to control this?

See the [Code Power Properties Guide](https://gitpitch.com/docs/code-features/pro-code-power-properties/#code-noblend-property). Specifically the **code-noblend** property.

> Sorry for the extra traffic on those issues, and thanks for the quick responses so far. 

No problem. It's late here so my day is just about to end. But hopefully the links I have shared will point you in the right direction.

**Comment by bwplotka** [comment]
This is so amazing thanks! Not sure how I missed those information in docs :grimacing: 

Let's close this issue, you solved all my questions. The only thing I am not sure is how to allow scroll - even without `code-noscroll` excessive code is just hidden (same with lines to length). Anyway, not a biggie I can zoom out and adjust, just this behavior is not aligned  with what's in docs:

> Sometimes the code that you want to present will extend horizontally or vertically beyond the extent of the available space for the code-block on your slide. In such cases, the default behavior is for the code-block to permit horizontal and/or vertical scrolling. And in many cases, this is the desired behavior.

Good night and thanks for quick help :medal_sports:

**Comment by gitpitch** [comment]
> The only thing I am not sure is how to allow scroll - even without code-noscroll excessive code is just hidden (same with lines too long). Anyway, not a biggie I can zoom out and adjust, just this behavior is not aligned with what's in docs...

Unfortunately that is *bit rot* in the docs. As you have found this is not the default behavior if you are using the [theme template](https://gitpitch.com/docs/themes/template). I'll need to correct that. The solution for you if you are still interested is as follows.

The default behavior for slide decks using the *theme template* is for *overflow* to be disabled by default for code blocks within those decks. This is the default because in most cases it makes for much nicer looking slides (no scrollbars are visible).

But you can override this default using a small snippet of [custom CSS](https://gitpitch.com/docs/themes/custom) for your deck. If you want to override the default behaviour *globally* for every slide in your deck you should activate the following CSS snippet:

```css
.reveal pre code { overflow: auto; }
```

By default, this property is set to *hidden*. So by setting it to *auto* you should be able to scroll through large source files. 

But we can do better. If you want to activate scrollbars for a large source file on a specific slide but leave the default behaviour of all other code slides unchanged, you can first declare a custom CSS class as follows:

```css
.code-scrollable { overflow: auto !important; }
```

And then you can activate this custom style on the specific code widget, like this:

```
@code[python code-scrollable](src/demo.py)
```

Hopefully one of these approaches -  the global solution or slide specific solution - will give you what you need.
