### ISSUE TITLE
Allow video embed with a timestamp

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#31]
On the 10th and 11th slides of [this presentation](https://gitpitch.com/Georgetown-University-Libraries/BarcodeInventory/master?grs=github&t=white), I have a link to a youtube video.  Ideally, I would like that embed to start at a specific timestamp.

On the 10th slide, I have a link with the proper timestamp, but the video does not open properly due to issue #30.

On the 11th slide, the embed option is lovely.  I noticed that YouTube does not generate embed codes with a start time.  I do not know if this could be controlled in GitPitch.

When I attempted to set a video as a [background video](https://github.com/gitpitch/gitpitch/wiki/Video-Slides#background) I was not able to pass a start time. 

If one of these options is implemented, it would be good to note the solution on the wiki page.

**Comment by gitpitch** [comment]
A new patch 38badea514cf12b0c33cf3e953a89ab2c28e887f has been pushed live on [gitpitch.com](https://gitpitch.com) that provides support for custom play `start` and `end` offsets for inline YouTube video playback.

To achieve the outcome you want for the sample presentation you linked to you can replace the following slide:

```
#VSLIDE
![Full Video](https://www.youtube.com/embed/5X_QiX-E7aI)
```

With a single slide that uses the new `start` parameter on the video URL:

```
![Video](https://www.youtube.com/embed/5X_QiX-E7aI?start=120)
``` 

The value you assign to `start` is a measure of seconds. For example setting `start=120` will cause the video to play from the 120 second (2 minutes) mark.

Note, when you use `start` on it's own your video will play from that start-offset to the end. When you can use `start` and `end` together a fixed period of the video will play, rather than the video play to the every end. For example:

```
![Video](https://www.youtube.com/embed/5X_QiX-E7aI?start=120&end=180)
```

This example would result in playback starting at 120 seconds for exactly 60 seconds. Then the video playback would automatically complete.

When you have a chance to test this functionality please let me know how it goes.

**Comment by terrywbrady** [comment]
That works perfectly for me.  Thank you!
