### ISSUE TITLE
Presentation 404: PITCHME.md not found in repo on GitHub.

### ISSUE THREAD

**Issue by curtcox** [gitpitch/gitpitch#312]
**Describe the bug**
I'm getting a 404 trying to publish my first gitpitch.
The error message provides inadequate help.

**To Reproduce**
Load https://gitpitch.com/curtcox/gitpitchtest

**Expected behavior**
The presentation should either work or provide more info about what I can do to fix it.

**Screenshots**
```
Presentation 404

PITCHME.md not found in repo on GitHub.
```
**Browser (please complete the following information):**
 - Chrome
 - Safari

**Operating System (please complete the following information):**
 - MacOS

**Additional context**
The error page isn't up to the task. It doesn't tell me what I might be doing wrong or how to fix it.
My first guess was that the feature was only available to paid users. Buying a plan didn't help.
My next guess was that I needed to add publish to the YAML. That didn't change anything.
Searching shows that this is a recurring problem.

https://www.google.com/search?q=gitpitch+presentation+404
https://github.com/gitpitch/gitpitch/issues?q=presentation+404+

There are 2 problems here. First, gitpitch.com keeps generating 404s when it shouldn't. Just as important, however, is that the 404 page doesn't provide adequate information about how to fix the problem. Should I be submitting this bug report? The 404 error page would be a great place to put an answer to that question.

**Comment by gitpitch** [comment]
Hi Curt, thanks for getting in touch and reporting these issues. Feedback inline.

> First, gitpitch.com keeps generating 404s when it shouldn't.

The reason you are seeing 404s is because the URL you are using for your slide deck is not pointing at branch that contains a `PITCHME.md`file. Hence 404 or Not Found.

The URL you are using is shown here:

>  https://gitpitch.com/curtcox/gitpitchtest

This URL is interpreted as follows:

- Find a `PITCHME.md` under the `curtcox` account
- In the root directory within the `gitpitchtest` repo
- Under the default `master` branch (default as no explicit branch is indicated)

When I look at your repo I see that your presentation files are found within a `main` branch. So the correct URL for your slide decks looks like this:

> [https://gitpitch.com/curtcox/gitpitchtest/main](https://gitpitch.com/curtcox/gitpitchtest/main)

Using this updated URL that takes into account the branch in which you are working you should have no difficulty viewing your slide deck.

> Second... the 404 page doesn't provide adequate information about how to fix the problem. 

Agreed, definitely room for improvement. So I have just pushed a patch to the live server on gitpitch.com to provide a more clear 404 message to help my users more quickly identify and fix these types of problems.

Here is a screenshot that shows the new message when the 404 occurs for your original link:

<img width="1407" alt="Not-Found-404" src="https://user-images.githubusercontent.com/19169584/95725966-38939a80-0c70-11eb-977f-dde17b3e9a68.png">

You can test out the new URL for your deck and you should find everything works as intended:

> [https://gitpitch.com/curtcox/gitpitchtest/main](https://gitpitch.com/curtcox/gitpitchtest/main)

David

**Comment by curtcox** [comment]
Thanks for the quick response. I was misled by repos/presentations such at this https://gitpitch.com/gitpitch/kitchen-sink#/ not having a branch name. I guess this would have worked if I had created the repo when github was still using the same default default branch name as gitpitch. If this mapping is explained in depth in the docs, a link to the appropriate doc page from the error page would be useful.
This exchange has solved this problem for me, but I fear the new error page will lead people to believe that they have to create a branch named "master" when that isn't the case.

- Curt

**Comment by gitpitch** [comment]
Curt, to address the additional issues you have raised I have made further updates to the `404` message. The `404` page now renders as follows:

<img width="1715" alt="Not-Found-404-v2" src="https://user-images.githubusercontent.com/19169584/95857084-fc853600-0d52-11eb-9b8e-78c88787af20.png">

The **Presentation URLs** link will take you to the [cloud service guide](https://docs.gitpitch.com/#/cloud/public-slide-decks) that explains how to properly construct URLs for any slide deck. It also includes details regarding conventions for decks maintained within branches named **master**.
