### ISSUE TITLE
Exception when accessing my slides.

### ISSUE THREAD

**Issue by bwplotka** [gitpitch/gitpitch#322]
**Describe the bug**

Accessing public URL gives: ![image](https://user-images.githubusercontent.com/6950331/99799796-2dfbd900-2b2b-11eb-8c4e-031c6cec5f14.png)

**To Reproduce**
Go to https://gitpitch.com/bwplotka/my/slides?p=slides/10 or https://gitpitch.com/bwplotka/my/slides?p=slides/optimizing-go-for-clouds/go-london-meetup-06-2020

**Expected behavior**
Everything works as in localhost using gitpitch docker (exactly same state of git repo): https://github.com/bwplotka/my/tree/slides/slides/10

**Screenshots**
![image](https://user-images.githubusercontent.com/6950331/99799796-2dfbd900-2b2b-11eb-8c4e-031c6cec5f14.png)

**Browser (please complete the following information):**
 - Chrome

Thanks in advance :hugs:

**Comment by gitpitch** [comment]
Hi Bartlomiej, thanks for reporting this issue. I will look into this and update the thread once I know more. Cheers, David.

**Comment by gitpitch** [comment]
Have you recently added the `gatoken` setting to the `PITCHME.yaml` for your slide decks?

This setting takes a `string` value. And because your token `2170247562 ` consists only of numbers it is being interpreted as an integer...which is considered invalid. You can fix this by being explicit about it being a `string` in your yaml file, like this:

```yaml
gatoken: "2170247562"
```

If this `gatoken` setting is newly added, please update it as described and let me know how it goes.

**Comment by bwplotka** [comment]
Ah yes! 

I recently changed, becuase Google Analytics introduced analytics 4: https://support.google.com/analytics/answer/9964640?hl=en 

I think the gitpitch is not ready for it yet (: (and that's fine it's super new)

I can get back to universal analytics (: Thanks

**Comment by gitpitch** [comment]
Ok. I recommend opening a new RFE to request support for Google Analytics 4 in GitPitch. We can use that RFE to see if it attracts many upvotes.

**Comment by bwplotka** [comment]
Actually all works. I just used wrong ID (: 


If I use the correct one all works.


Correct one is here: 

![Uploading image.png…]()

**Comment by gitpitch** [comment]
😄
