### ISSUE TITLE
"href" link may not work sometimes

### ISSUE THREAD

**Issue by sogaoh** [gitpitch/gitpitch#325]
**Describe the bug**
"href" link may not work sometimes

**To Reproduce**
Example presentation : https://gitpitch.com/sogaoh/GitPitchPractice?p=20201129-link-after-br-test
Source : https://github.com/sogaoh/GitPitchPractice/tree/master/20201129-link-after-br-test

**Expected behavior**
"href" link always work

**Screenshots**
![gitpitch_20201129](https://user-images.githubusercontent.com/2090887/100533702-b0327e80-324a-11eb-9a1b-08dfab6cddba.gif)

**Browser (please complete the following information):**
 - Chrome
 - Firefox
 - Safari
 
**Operating System (please complete the following information):**
 - MacOS
 
**Additional context**
None.

**Comment by gitpitch** [comment]
Hi Hisashi, thank you for reporting this issue.

The reason your link is not working is because on your current slide the **(OK)** layout block overlaps the **(NG)** layout block. And that overlap prevents the mouse hovering over the link in the **(NG)** layout block.

To help you understand (see) this more clearly I have added a simple [background color](https://docs.gitpitch.com/#/grid-layouts/backgrounds) to each of the layout blocks on your sample slide:

<img width="1306" alt="slide-1" src="https://user-images.githubusercontent.com/19169584/100538110-95014800-3225-11eb-8838-ccdeef337b82.png">

You can see how the **(OK)** layout block (the yellow block) completely overlaps the link content in the **(NG)** layout block (the red block).

To ensure links work correctly the *solution* is to size each layout block so it more accurately fits the content in that block. And proper sizing of layout blocks helps to ensure that your layouts blocks do not overlap each other.

For example, here is a modified version of your sample slide. I have changed the size of the layout blocks used to render your content:

<img width="1350" alt="slide-2" src="https://user-images.githubusercontent.com/19169584/100538241-751e5400-3226-11eb-8625-cf9a924f5d7a.png">

You can see in the markdown snippet above how the new sizes for the layout blocks are chosen to better fit the content within those blocks. You could further simplify your slide by using a single layout block to render the **(NG)** and **(OK)** content as a single unit:

<img width="1350" alt="slide-3" src="https://user-images.githubusercontent.com/19169584/100538275-af87f100-3226-11eb-80b9-008fe289463f.png">

The final slide markdown and content would then look like this:

<img width="1350" alt="slide-4" src="https://user-images.githubusercontent.com/19169584/100538304-d3e3cd80-3226-11eb-99b0-983e33b70468.png">

The most important thing to remember is that you must control the *size* of your layout blocks. Temporarily using a simple *background color* as I have shown above is a great way to *visualize the exact size of any block*. The colors can also help you to see if there is any overlap between your blocks.

I hope this helps. Cheers, David.

**Comment by sogaoh** [comment]
Thank you for the explanation!
I've understood.
