### ISSUE TITLE
Override link to repository in presentation

### ISSUE THREAD

**Issue by mike-ward** [gitpitch/gitpitch#4]
Use case:

I use a separate repo for my `gh-pages` site for http://markdownedit.com (mike-ward/mde-site). It's easier than switching branches and waiting for Git to resync.

**Comment by gitpitch** [comment]
Need a little more info here. Override what link exactly? I'm also not sure I have enough context to understand what you mean by "It's easier than switching branches and waiting for Git to resync"?

You can add a link on any slide that links to external sites etc. You can even have those links open up in another browser window rather than redirect away from your slideshow, see the [HTML Slides](https://github.com/gitpitch/gitpitch/wiki/HTML-Slides) page in the GitPitch Wiki for details.

For example, see the final slide of this [GitPitch Presentation](https://gitpitch.com/onetapbeyond/lambda-spark-executor).

**Comment by mike-ward** [comment]
In the presentations in the lower right corner. Thought it was a link but it's just text.

![image](https://cloud.githubusercontent.com/assets/567927/17978136/9d9033a2-6ac2-11e6-9526-f941f42e6859.png)

**Comment by gitpitch** [comment]
I'm going to close out this issue as not and issue for now. Feel free to open it again with additional info if you feel your concern has not been fully addressed.
