### ISSUE TITLE
Exporting to *.pdf does not preserve monospace font of code snippets

### ISSUE THREAD

**Issue by rogalski** [gitpitch/gitpitch#43]
MCVE for bug: https://github.com/rogalski/gitpitch-bug-mcve
OS: Mac OS Sierra
Browsers:
Safari 10.0.3 (12602.4.8)
Chrome 56.0.2924.87 (64-bit)

**Comment by gitpitch** [comment]
Hi @rogalski 

It looks like the issue you've described stems from a [known issue on decktape](https://github.com/astefanutti/decktape/issues/67). The `decktape` service provides the backend printing functionality for GitPitch.

Basically `decktape` requires a concrete monospace font family to be defined in the css for any page that is attempting to print in monospace. It turns out the [reveal.js](https://github.com/hakimel/reveal.js/) default themes used to render your GitPitch presentations do not specify a concrete monospace font family for `code` and `pre` blocks. And it is those blocks that render your code snippets.

Fortunately GitPitch supports custom css overrides for any presentation so we can fix this problem ourselves. Adding custom css to your presentation is [detailed on the Wiki here](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS).

The `GitPitch.com` server has numerous fonts installed, including the `Inconsolata` font which supports monospace. So if you add your own custom `PITCHME.css` to your repo you can then use the following css snippet:

```
.reveal code, .reveal pre {
    font-family: Inconsolata, Regular, monospace;
}
```

This override should ensure that your code blocks have a concrete monospace font family specified which should then allow `decktape` to print as expected.

Remember to add an appropriate value to the `theme-override` property in your `PITCHME.yaml` so your custom css can be picked up at runtime. Something like this:

```
theme-override : assets/css/PITCHME.css
```

Try it out and let me know how it goes.

**Comment by rogalski** [comment]
Hello,

Adding those overrides and custom CSS works fine as a workaround.

**Comment by ahangchen** [comment]
I found that export pdf on server loss fonts for Chinese, while Chinese are supported when viewed on the browser.
What's more, why export pdf on browser doesn't split the slides.

**Comment by gitpitch** [comment]
Chinese fonts are not currently installed on the `gitpitch.com` server which is why exporting to PDF on the server does not render those fonts.

The preview you see in your browser window when exporting to pdf in the browser often shows the content without separation between slides. But if you go ahead and save the PDF to disk the save presentation will sometimes still render correctly. Can you try this and let me know if it works.

**Comment by ahangchen** [comment]
When use "export pdf on browser", there are no any buttons on the page to save the PDF to disk. If you means CTRL+P to print it. The slides has separation again, but doesn't contain background and many other CSS.

**Comment by gitpitch** [comment]
@ahangchen there are indeed no buttons on the page but there are instructions on the GitPitch Wiki for how you "export pdf on browser", [see here](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Printing). You start with CTRL+P. 

As for printing your specific presentation, I have no immediate solution I can give you on `gitpitch.com` so if this is critical path for you then you may need to use another presentation tool. If I do find a solution for `gitpitch.com`, I will update this thread.

You can of course spin up a GitPitch server on your local machine. Your local machine no doubt has the required fonts for your presentation so "Generate PDF on Server" would again become an option for you. You could use your local server for printing to PDF while continuing to use `gitpitch.com` for sharing your online slideshow. Again, see the GitPitch Wiki [build and launch from source](https://github.com/gitpitch/gitpitch/wiki/Server-Build-Instructions#build-and-launch-from-source).

**Comment by ahangchen** [comment]
@gitpitch My pdf generated on server has the same look with your version. 

The characters missed are all Simplified Chinese, the characters can be presented are all shared between Traditional Chinese and Simplified Chinese. I think this a problem about fonts, maybe your fonts on server only support Traditional Chinese. Most Chinese use Simplified Chinese and usually fonts supporting Simplified Chinese also support Traditional Chinese, like Microsoft YaHei.

**Comment by gitpitch** [comment]
@ahangchen thanks for this feedback, very helpful. I am now trying to find out how I can install font support on a Ubuntu 14 server for Simplified Chinese. If you or any of your colleagues know how to install these fonts (at the command line) on Ubuntu 14 can you please let me know here so I can apply that update.

**Comment by ahangchen** [comment]
Down the fonts: xx.ttf

```
cd /usr/share/fonts
mkdir custom_font
chmod 755 custom_font
cp xx.ttf /usr/share/fonts/custom_font
sudo fc-cache -f -v
```

Maybe this [reference](https://wiki.ubuntu.com/Fonts) will also help.

**Comment by gitpitch** [comment]
Thanks. I've already applied a number of east Asian fonts on my staging server and will test shortly. If those tests are successful I will apply the same patches on `gitpitch.com`. I'll update this thread once I have the results of this stage testing.

**Comment by gitpitch** [comment]
Ok @ahangchen can you please review the attached PDF and let me know how it everything looks.
[PITCHME.pdf](https://github.com/gitpitch/gitpitch/files/972381/PITCHME.pdf)

**Comment by gitpitch** [comment]
The production server `gitpitch.com` has been updated with support for Chinese (both Simplified and Traditional), Japanese and Korean fonts. @ahangchen if can can view and confirm your presentation is now correctly rendering all Simplified Chinese characters from `gitpitch.com` then I will close this issue as resolved.

**Comment by ahangchen** [comment]
Yes my slides now is correctly rendering all characters. Thank you. :smile:
