### ISSUE TITLE
Exporting to *.pdf does not preserve Emojis

### ISSUE THREAD

**Issue by rogalski** [gitpitch/gitpitch#44]
MCVE for bug: https://github.com/rogalski/gitpitch-bug-mcve
OS: Mac OS Sierra
Browsers:
Safari 10.0.3 (12602.4.8)
Chrome 56.0.2924.87 (64-bit)

**Comment by gitpitch** [comment]
Hi @rogalski 

It looks like the issue you've described stems from a [known issue on decktape](https://github.com/astefanutti/decktape/issues/67). The `decktape` service provides the backend printing functionality for GitPitch.

Basically `decktape` requires a concrete monospace font family to be defined in the css for any page that is attempting to print in monospace. It turns out the [reveal.js](https://github.com/hakimel/reveal.js/) default themes used to render your GitPitch presentations do not specify a concrete monospace font family for `code` and `pre` blocks. And it is those blocks that render your code snippets.

Fortunately GitPitch supports custom css overrides for any presentation so we can fix this problem ourselves. Adding custom css to your presentation is [detailed on the Wiki here](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS).

The `GitPitch.com` server has numerous fonts installed, including the `Inconsolata` font which supports monospace. So if you add your own custom `PITCHME.css` to your repo you can then use the following css snippet:

```
.reveal code, .reveal pre {
    font-family: Inconsolata, Regular, monospace;
}
```

This override should ensure that your code blocks have a concrete monospace font family specified which should then allow `decktape` to print as expected.

Remember to add an appropriate value to the `theme-override` property in your `PITCHME.yaml` so your custom css can be picked up at runtime. Something like this:

```
theme-override : assets/css/PITCHME.css
```

Try it out and let me know how it goes.

**Comment by gitpitch** [comment]
Custom fonts, which includes Emoji fonts, are not supported. I'm closing this issue as will not fix.
