### ISSUE TITLE
Add history option to enable direct links to slides

### ISSUE THREAD

**Issue by chbndrhnns** [gitpitch/gitpitch#48]
There is a history flag for reveal.js that enables that every slide has its url like http://localhost:8080/pitchme.html#/1.

I'd like to see this in gitpitch, as well

**Comment by gitpitch** [comment]
Hi @chbndrhnns check ou the [Slide Direct Links page](https://github.com/gitpitch/gitpitch/wiki/Slide-Direct-Links) in the Wiki. I think that should give you what you need, right?

**Comment by chbndrhnns** [comment]
Yeah, but could there be an option in PITCH.yaml to append the slide-specific urls automatically so that I can just copy/paste?

**Comment by gitpitch** [comment]
@chbndrhnns the option you requested has been added and this support is now live. To further simplify matters I've decided to make this `history` option enabled by default so you do no have to do anything in order to have access to the direct links for slides within your presentations.

You will still need to construct and use a direct URL to your slideshow as described on the [Slide Direct Links page](https://github.com/gitpitch/gitpitch/wiki/Slide-Direct-Links) in the Wiki. But the slide specific coordinates will now be generated for you.

If you need to disable this `history` feature for any reason just set the following property in your `PITCHME.yaml`:

```
history: false
```

**Comment by gitpitch** [comment]
Requested feature now supported. Resolved by 787d2cc27bc1b3f7ba4cd25d14aa5cea4c38a337.
