### ISSUE TITLE
---?include=relative/path/file.md for composable slideshows

### ISSUE THREAD

**Issue by freddi301** [gitpitch/gitpitch#51]
along with https://github.com/gitpitch/gitpitch/issues/52 one can achieve reusable slides

**Comment by gitpitch** [comment]
Hi @freddi301 thanks for your feedback, this is an interesting feature request. However the feature as described would add considerable complexity for what in my experience of typical usage would be a real edge case.

As noted in my comment on #52 you can easily maintain multiple slideshows in a single repo. I know this won't give you reusable slides as requested but it should greatly simplify managing related content across multiple slideshows.

**Comment by freddi301** [comment]
Hi, i don't know how hard it can be to implement it.
I was thinking that i can add a build step to my project that replaces #INCLUDE with the content of related file.
I am writing a programming course, and i will teach it to different skill level classes, so ti would be handy to have this feature to just include/exclude content by need.
Anyway this feature could be optional so no problems for tipical usage.
While my use-case could be an edge case, consider this feature request on the long run and don't close the issue.
Thank you, i'm enjoing gitpitch :smile:

**Comment by freddi301** [comment]
Hi,
i see that there are a feature like i requested already for gists and images, i propose something like
```
---?include=horizontal/slide.md
+++?include=vertical/slide.md
```

**Comment by gitpitch** [comment]
Hi @freddi301 again thanks for all the feedback.

Unlike gists and images, markdown requires special server-side `preprocessing` before it can be used to generate the slideshow that you see in your browser. So the handling of `---?include=path/slide.md` is quite a bit more complex than simply handling gists and images. Not impossible, just not trivial.

I'll leave this issue open and if I get to implementing this feature I will update the issue and let you know.

Please keep me informed of your progress with your programming course, it sounds very interesting and I'm glad to hear you are enjoying using GitPitch. Is your course associated with a university?

**Comment by gitpitch** [comment]
Hi @freddi301 I have prototyped a solution that is available for you to try out that should allow you to build fully composable presentations using `Markdown includes` to build out the content of your slideshow.

GitPitch now supports the following new `delimiter` arguments for horizontal and vertical includes respectively:

```
---?include=path/to/some.md
```

```
+++?include=path/to/other.md
```

See the following [sample presentation](https://gitpitch.com/gitpitch/feature-demo/composable-markdown) for a demonstration of how you can use this new feature.

As you will see this sample presentation takes the full content of the `Kitchen Sink` presentation and breaks out each feature into it's own markdown file. The main `PITCHME.md` file then declares the necessary include statements in order to pull all of the feature details into the main presentation.

This feature is live on [gitpitch.com](https://gitpitch.com). I do still consider this feature to be experimental. Your testing and feedback will help with my decision as to when to promote this feature into `master`. Let me know how it goes.

**Comment by freddi301** [comment]
Hi @gitpitch ,
the basic `---?include=path/file.md` works fine.M
I did not have time, did you add a guard against circular dependency?
A simple singleton mechanism would be ok, example:
GITPITCH.md
include slideA.md
include slideB.md

slideA.md
include slideC

slideB.md
include slideA

you could create map of singletons, so a slide that is included more then once, will appear only where included the first time and optionally a link to the related slide the other times. This makes sense as if you teach something that has slides in common to another course.

The slideshow is here https://github.com/freddi301/h5c3j5-course
I replicated a bit of gitpitch functionality on clientside here https://freddi301.github.io/h5c3j5-course/?h=0&v=0

**Comment by gitpitch** [comment]
Hi @freddi301 as only the master `PITCHME.md` is currently eligible for `include` processing there is no risk of circular dependencies.

The example presentation structure you described is not supported as you are using the `include` mechanism outside of your `PITCHME.md`.

**Comment by freddi301** [comment]
Perfect :+1: 
Great work, it's what i need

**Comment by gitpitch** [comment]
Modular, composable presentation markdown feature provided by commit 2b11bc310f255cee4ca2e4997b6060f7809fd63c.
