### ISSUE TITLE
Slideshow Speaker Notes support?

### ISSUE THREAD

**Issue by dukedave** [gitpitch/gitpitch#56]
This is a feature request:

So I assume it's okay, albeit not explicitly stated in the docs (to my knowledge) to include comments in a `PITCHME.md`, whether that be:

* [HTML comments](https://www.w3schools.com/html/html_comments.asp) or
* [Markdown hackery](http://stackoverflow.com/q/4823468/21115).

If so, then would you consider adding some kind of export where I can see a thumbnail of each slide, next to any comments for that slide?

The end goal would be something like [slide preview and annotations](https://softwarerecs.stackexchange.com/questions/24681/pdf-presentation-software-with-preview-of-next-slide-and-annotations).

**Comment by dukedave** [comment]
Something like [Jekyll's front matter](https://jekyllrb.com/docs/frontmatter/) could also work.

**Comment by gitpitch** [comment]
Thanks for the feedback @dukedave nice idea. But right now this kind of speaker notes feature is not something I have the cycles for but I'll keep the issue open and get back to evaluating it when time permits.

**Comment by dukedave** [comment]
Okay great!
I understand totally 😄

**Comment by sammoorhouse** [comment]
I've been littering my slides with HTML comments which are (correctly!) ignored by the renderer, but it'd be great if a per-slide or presentation-level notes section could be shown by an alternative renderer.

One of the up-sides, for me, of having markdown as the golden source is that it forces you into a kind of "powerpoint-lite" model of presentation. You can't rely on reading the slides for direction; you must know the material. Well, that requires a way for the author to communicate the narrative to the presenter.

I've been solving this with github wiki, which sits quite well alongside the slide markdown itself. But it's like comments in code - they get out of date, people forget to check for updates, and if you distribute or print your slide deck, the notes aren't *right there*.

So a +1 for @dukedave's request, a high-five for @gitpitch for an awesome product, and a resolute thumbs-down for "[//]: <> (This is also a comment.)"!

**Comment by onetapbeyond** [comment]
I've just activated the reveal.js speaker-notes feature for all GitPitch offline presentations. As I have not yet had time to update the Wiki here are the steps you need to follow in order to use this new feature. You can use a sample presentation that includes speaker-notes so you can see exactly how this works:

1. Add speaker-notes for some or all of your slides in your `PITCHME.md`
2. Once you have pushed your `PITCHME.md` open your presentation on `gitpitch.com`.
3. Click `Offline` to download your offline presentation bundle (zip archive)

Use https://gitpitch.com/onetapbeyond/gen_metrics to test a sample presentation that includes speaker notes in the markdown.

4. Open the offline presentation bundle (zip archive) on disk
5. Follow the [Slideshow Offline](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Offline) Wiki instructions to open and view the presentation
6. Once your offline presentation is open in your browser, press the `s` key on your keyboard
7. The new speaker-notes view will pop-open into a new window
8. Enjoy ;-)

Again, here is a link to a sample presentation:

https://gitpitch.com/onetapbeyond/gen_metrics

It just happens to be a presentation for another project that I'm working on and it shows my real notes. Even if you're not interested in the specific content of this project, you will see just how simple it is to add notes to your presentations and then enjoy the new speaker-notes view which you can use to drive and pace your talks.

**Comment by sammoorhouse** [comment]
Incredible.

**Comment by gitpitch** [comment]
Thanks :) Btw, here is a screenshot for anyone reading this thread so they can get a sense of what's now available when you activate speaker-notes for any GitPitch offline presentation:

![speaker-notes-grab](https://cloud.githubusercontent.com/assets/19169584/25553430/fefe5074-2cdc-11e7-9892-d8d12f470854.png)

**Comment by gitpitch** [comment]
Wiki has been updated with complete documentation for this [new speaker notes feature](https://github.com/gitpitch/gitpitch/wiki/Speaker-Notes-Window).

**Comment by gitpitch** [comment]
Quick update on thread. I've just announced support for live speaker notes for **all online and offline** GitPitch presentations. See blog post for details:

https://medium.com/@gitpitch/presentation-speaker-notes-for-everyone-19bdc67b1910
