### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by Y-Less** [gitpitch/gitpitch#59]
It would be very useful to have links directly to one state of one slide on one commit (especially for submitting bugs) as then people can point to the exact part of the exact slide they want.  For example, I was going to post a bug, with an example from the kitchen-sink slide show.  Instead of being able to link to exactly which slide it happens on, I need to say that it is the 12th slide along, 3rd slide down (in the current revision, assuming that doesn't change).  Permalinks on github are `y`, maybe copy that?

**Comment by gitpitch** [comment]
You can use the SHA for any commit in-place of a branch name (in fact, SHA is a branch name) on a GitPitch slideshow URL in order to ensure that everyone is looking at a specific version of the slideshow.

For example, the following is a valid GitPitch URL:

```
https://gitpitch.com/gitpitch/gitpitch/ac97fe1eb61c6e6af704533ae3a1795540954973
```

This example link points to a specific version of the slideshow that was created by the commit indicated on October 13, 2017.

This link will remain valid no matter how content in the repo moves forward. So if you share this style of link you can be sure that everyone is looking a specific version of the slideshow. In this way you can easily report a bug (against a specific version of a slideshow) or simply share a link to a frozen version of any slideshow.

Given (1) commit SHA are branches and (2) you can construct GitPitch URLs easily for any branch, you can easily construct a permalink to any presentation.
