### ISSUE TITLE
Local development mode

### ISSUE THREAD

**Issue by Krever** [gitpitch/gitpitch#64]
Is it planned to support some way of using gitpitch without having to push commits into repository? 

When developing the presentation it would be nice to be able to shorten the feedback loop.

Or maybe you could advice how hard it would be to add such feature to gitpitch server? I'm rather familiar with play framework so I may consider contributing if it's not very big change.

**Comment by gitpitch** [comment]
Hi @Krever check out [Developing / Testing Locally](https://github.com/gitpitch/gitpitch/wiki/Developing-Testing-Locally) on the GitPitch Wiki. This should give you one way to shorten the feedback loop.

**Comment by Krever** [comment]
That's great, thanks! This solves my issue ;)

**Comment by gitpitch** [comment]
Great. Closing issue as resolved.

**Comment by augnustin** [comment]
The solution you provide here seems fair but still requires some tweaks to work. 

From my gitpitch-agnostic perspective, the cleanest architecture for me would be to have the presentation engine as a module (eg. node module) so that everybody can work locally by simply running `npm install gitpitch --save` and `npm run gitpitch`.

Then gitpitch.com would simply be the hosted version of the project, like wordpress, github pages etc.

I am aware you are using java which might be harder to modularize (don't know about it), but maybe there are other technologies you like to play around with those days!

Cheers

**Comment by gitpitch** [comment]
Augustin, thanks for this additional feedback. 100% agree the current approach to working offline with GitPitch is not ideal. Offline bundles were designed to be and are delivered as static bundles. Not really designed as a development environment. But today that's all we've got so I documented how they can be used to facilitate offline dev.

What GP needs is a dedicated tool for offline development. That is already in the works. And it will get my full attention once I push the upcoming GitPitch Pro release.
