### ISSUE TITLE
GitPitch Offline mode not working

### ISSUE THREAD

**Issue by orclev** [gitpitch/gitpitch#68]
Clicking on the offline link from any presentation results in an error page saying that offline mode is currently unavailable. 

Unfortunately it appears as if the speaker notes feature can not be used except in offline mode.

Ideally speaker notes would be usable even in online mode, but barring that it would be nice if offline mode was either fixed, or else if there was some kind of documentation on what to do when offline mode is unavailable.

**Comment by gitpitch** [comment]
Hi @orclev thanks for reporting this problem and sorry for the inconvenience. It turns out one of the SSL certs on the gitpitch.com server had literally just expired and was causing some trouble for a number of the backend services, including the offline service. I've just fixed the problem and all services, including offline, should now be back up and running.

Speaker notes are dependent taking your presentation offline. This is not something that can be offered any other way.

I'm closing issue as resolved. Please open again if you are still experiencing the problem.

**Comment by orclev** [comment]
Thanks, looks like it's working now. It's unfortunate that speaker notes can't be made to work in online mode, but I understand that there are technical reasons that make that difficult.
