### ISSUE TITLE
Theme overrides stylesheet should not be HTML escaped

### ISSUE THREAD

**Issue by jroper** [gitpitch/gitpitch#7]
The theme overrides stylesheet is embedded directly inside the generated HTML page for the presentation.  This is fine, except that it is HTML escaped.  Content inside style tags should not be HTML escaped, escaping it means selectors like `ul > li` break.

**Comment by gitpitch** [comment]
Thanks for reporting this @jroper Can you point me at an example slideshow (using your custom css) that exhibits this problem?

**Comment by jroper** [comment]
https://gitpitch.com/pitchme/slideshow/github/jroper/microservices-architecture/master?t=white

Note in the head:

```
.image-fragments &gt; div {
    position: absolute;
    left: 0;
    top: 0;
}
```

The `&gt;` shouldn't be escaped, it should be `>`.

**Comment by jroper** [comment]
The effect of this is that that style doesn't get applied, which means the images in my presentation aren't stacked on top of each other (which is the effect of that styling when applied correctly).  They're meant to appear effectively as an animation.

**Comment by gitpitch** [comment]
Thanks for the detailed feedback @jroper. I'll look into this and update the thread just as soon as I have something concrete for you.

**Comment by gitpitch** [comment]
Custom css is now handled as an external stylesheet rather than as an embedded style. This prevents the type of escaping problems described here. A patch has been pushed live on [GitPitch.com](https://gitpitch.com). @jroper I like [your slideshow animations](https://gitpitch.com/jroper/microservices-architecture). If you can confirm your slideshow is now functioning as expected can you please close out this issue. Thanks.

**Comment by jroper** [comment]
I can confirm it's fixed, thanks!
