### ISSUE TITLE
Exporting background/inline images in generated PDF

### ISSUE THREAD

**Issue by bergercookie** [gitpitch/gitpitch#83]
Seems that, by default, the PDF generation, skips the background images that I have placed in my presentation. Is there an option (e.g., in the yaml file) to alter this?

fwiw, I had a similar issue with the rendering of MathJax equation in PDF, but I followed the instructions provided in [this issue](https://github.com/gitpitch/gitpitch/issues/45) and dealt with it.

The presentation at hand can be found here: https://gitpitch.com/bergercookie/mastert_present/tmp

Thanks,
Nikos

**Comment by gitpitch** [comment]
Hi @bergercookie thanks for your feedback. So background images should appear in the PDF, they are not purposely skipped by default. But there is definitely a problem here when using the `Generate PDF in Browser` option. And I have just reproduced this problem using another presentation so this is a general problem, not one specific to your presentation.

I do not have a fix for you at this moment. The only workaround I can suggest is that you use the `Generate PDF on Server` option which will display your background images. I understand you will not get the best fonts for your MathJax formulas using this approach. I'll keep this issue open and if I find a solution I'll update this thread.

**Comment by bergercookie** [comment]
Thanks for your prompt response to this @gitpitch.
Let me know, should this be resolved.

**Comment by gitpitch** [comment]
Hi @bergercookie this issue has been resolved and the fix is live. As a consequence of this fix when you use the `Generate PDF in Browser` feature you should now see all of your background images and you can also avail of the nice fonts when rendering MathJax formula.

This is an important fix for everyone using this service so thank you again for reporting it. Whenever you can verify the fix we can close out this issue.

As a final side note, I see you have an additional (superfluous) slide delimiter in your markdown, see the following snippet from your `PITCHME.md`:

```
---

### SLAM Commercial/Academic Usages

- Self-driving cars |
- Domestic robots (Roomba, Neato) |
- Architectural applications (GeoSLAM) |
- Large-scale mapping applications (UAV Atmos) |
- Space applications (NASA Planetary Rovers) |

---

---?image=assets/figures/bulk/roomba.jpg&size=contain
``` 

The `---` delimiter that appears before the `---?image=` delimiter is not needed and can (and probably should) be deleted. It currently creates a blank slide in your presentation.

**Comment by bergercookie** [comment]
Hi @gitpitch,

>Hi @bergercookie this issue has been resolved and the fix is live. As a consequence of this fix when you use the Generate PDF in Browser feature you should now see all of your background images and you can also avail of the nice fonts when rendering MathJax formula.

Great! Thanks for getting back to this so soon!
Indeed, exporting images works correctly now.

>As a final side note, I see you have an additional (superfluous) slide delimiter in your markdown, see the following snippet from your PITCHME.md:

Thanks for noticing!

Closing this...
