### ISSUE TITLE
Feature request: allow relative URLs for SVG images

### ISSUE THREAD

**Issue by khinsen** [gitpitch/gitpitch#95]
Motivation: absolute URLs prevent both local offline development and fully offline presentations, i.e. presentations in the absence of an Internet connection.

I found a workaround for local offline development: use HTML img elements, where relative URLs work. The relative URLs are then replaced by absolute ones (using a [RawGit](https://rawgit.com/) pointing to my repository on GitHub) before committing PITCHME.md, using a sed one-liner.

**Comment by gitpitch** [comment]
Hi @khinsen thanks for your feedback and this feature request.

In order to render an SVG image using a HTML image tag the file content must be served with a valid `Content-Type` header. In the case of SVG that header values is `image/svg+xml`.

However, for security reasons, the leading Git hosting services purposely avoid setting this header when serving raw SVG file content.

As a result of this, relative URLs to Git repository files can not be used for SVG content, as the corresponding absolute URLs generated by GitPitch to the files hosted on the Git service are _guaranteed-not-to-have-the-required-content-type-header_.

The reason your RawGit workaround works is simply because RawGit does set a valid `Content-Type` header for SVG files. But RawGit is limited to only files hosted in GitHub repos. And GitPitch aims to support a wide selection of Git services, currently including GitHub, GitLab, Bitbucket, GitBucket, Gitea and Gogs. So directly using a third party service like RawGit is not an option for GitPitch.

I know this is not the answer you were hoping for, but I do not currently see any alternative to your sed one-liner or some equivalent pre-preprocessing when working with SVGs as you've described.

**Comment by khinsen** [comment]
Thanks @gitpitch for this clear explanation of the problem!

A long-term solution (perhaps I'd better say a long-term workaround) would be for GitPitch to provide itself the service of RawGit, but for all supported Git hosting services.

The real solution would be for W3C to define a safe subset of SVG that would probably be sufficient for 99% of real-life use cases.

**Comment by gitpitch** [comment]
Thanks again @khinsen for your feedback.

Your suggested long-term workaround makes sense. It is something I've considered in the past but decided, for the present at least, that it falls out-of-scope for planned extensions to GP.

That said, it sill may happen sooner than any change we could hope to see from the W3C :)

**Comment by gitpitch** [comment]
@khinsen just a quick update on this thread. The newly released GitPitch Pro (now in beta) supports SVGs served directly from public and private Git repos. Works across all Git providers: GitHub, GitLab, and Bitbucket.

**Comment by khinsen** [comment]
@gitpitch Thanks for the info - that sounds good!
